### ISSUE TITLE
Schedule interviews with G&A IT leadership, engineers, and architects 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#10]
**Background**
We want to talk to various IT stakeholders to understand their work. 

**Acceptance criteria** 
- [x] Interviews with at least 2 NRM engineers and architects have been scheduled
- [x] Interviews w/ at least 2 IT stakeholders have been scheduled

**Tasks**
- [x] Get list of possible contacts from G&A point of contact
- [x] Draft recruitment email text
- [x] Send scheduling emails
- [x] Send confirmation emails

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
@neilmb and @donnykwan here are notes from some old interviews with some current stakeholders that y'all would probably find helpful to skim over in advance of any interviews in the near term. 
[Interview w/ architect](https://docs.google.com/document/d/1A2uSrgylR12IaUhdti-3lp3VjSJ31fZXn1HdlFJ4tYk/edit#)
[Interview with stakeholder in OCIO](https://docs.google.com/document/d/1GM5i2vrdqOBU9wUQ1-eHD_X5xnV4B8pURaXsewTzlUI/edit#)
