### ISSUE TITLE
Publish draft RFQ for comment

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#103]
**Background**
We want to learn more about the vendors on the DAITSS BPA, so we're going to submit a draft RFQ. 

**We'll know we're done when...**
- [ ] We've ~published~ provided everything that is needed for the COR to publish a draft RFQ that reflects what we know about the to-be project

**Tasks**
- [x] @MCHopson spins up template
- [x] Schedule co-working time for Mark and Melissa to refine async contributions
- [x] Review with Jay and team
- [x] Refine based on feedback
- [x] Share draft with Nick (related issue: #97)
~- [ ] Publish~

**Comment by MelissaBraxton** [comment]
Draft is [here](https://docs.google.com/document/d/1ih6pN-HHsbf7FcupdY5R3Wa4odH7EHP0/edit#)

**Comment by MelissaBraxton** [comment]
Waiting for team feedback.

**Comment by MelissaBraxton** [comment]
Updated to remove "publish" from the tasks. It hasn't happened yet, but we're given the COR everything we can/they will need, and is now in their hands.
