### ISSUE TITLE
Help make document for FS CIO work intake process

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#106]
**Background**

FS CIO has a new portal-based process where business units can input the projects that they need from CIO. There's a template word doc and then the results are pasted into a web app. Heather wants us to do this as soon as possible and Jay could use some help translating our PA documents into the right answers for the various fields in that template

**We'll know we're done when...**
- [x] Jay has submitted the "application" in the web app 

**Tasks**
- [x] Work on the Word doc asynchronously to get it ready
- [x] Sit down for some co-working with Jay on Teams

**Comment by neilmb** [comment]
Worked on this with Jay. He is getting approval from Chris and then submitting it online with the FS.

**Comment by allisonnorman** [comment]
@neilmb - Do you want to keep this in waiting until we hear back or can we close this since it's been submitted?

**Comment by neilmb** [comment]
Close after it's submitted
