### ISSUE TITLE
Document our understanding of the Path Off Of Oracle (TM)

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#108]
**Background**

NRM has a medium-term priority on getting entirely out from under Oracle. We have an understanding of how our modular modernization for G&A will relate to that. We should write it down and share it with FS so they understand where this project is, and also to help them think through similar issues with other NRM apps.

**We'll know we're done when...**
- [ ] We have a document of our current understanding that we all like and have sent to Heather

**Tasks**
- [ ] Write a draft in Google Docs capturing what we talked about in our strategy meeting time.
- [ ] Get eyes from our team to look at the draft and polish it, but not too far
- [ ] Send the polished version to Heather as a PDF. Maybe attach it to a weekly ship email as well?

**Comment by allisonnorman** [comment]
Couple notes from when this came up in our retro:
- Let's document first and then think about whether we want to check back in with Sue & Heather 
- One possibility: In RFQ - Add something about the ability for vendors to help move away from legacy. Or  “here is what we did, how would you move it forward, what are the risks you see going forward?”
