### ISSUE TITLE
Clean up models based on Jamie's feedback

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/NRM-Grants-Agreements#111]
**Background**
Jamie has promised a spreadsheet detailing all the model fields and what they're used for. Based on that spreadsheet, we should further clean and refine our models to provide better feedback and an improved experience

**We'll know we're done when...**
- [ ] Model fields are appropriately documented and understandable.
- [ ] 

**Tasks**
- [ ] Group fields by purpose
- [ ] Provide helpful labels and help text
- [ ] Fields that should not be user editable should not be editable
