### ISSUE TITLE
Establish communication practices w / legacy team and Product Manager

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#112]
**Background**
Aaron Burk, former Open Forest PM is now working with the G&A team as a PM (yay!) We want to figure out how to best incorporate him into the work we're doing and establish practices of communicating with him and the legacy G&A dev team. 

**We'll know we're done when...**
- [x] We have an understanding of how we'll collaborate with the G&A legacy team and PM.
- [x] We've invited Aaron to relevant meetings and have updated him on where we are in the project and what's next. 
- [x] Jay and Aaron have met and have an understanding of the roles of PO and PM on this project.

**Tasks**
- [X] Add Aaron to weekly ship distro list
- [x] Schedule intro chat. 
- [x] Invite Aaron to sprint demos
- [x] Introduce PM/PO concepts with Jay in 1:1 ([ref](https://docs.google.com/presentation/d/1R8JAp3jph0E58LJFmUw0WDJMkkdJfAHEhpX9moehods/edit#slide=id.g58906c32dc_0_32))
- [x] Meet with Aaron to understand his new role, and identify ways of collaborating with legacy team. 
- [x] Update team on point above. 
- [x] Add Aaron to partner channel (form submitted 3/26)

**Comment by allisonnorman** [comment]
Closing this as it's a dupe for #116

**Comment by allisonnorman** [comment]
Jay and I met with Aaron on Thursday. Some takeaways from that convo:

Some takeaways from the intro coffee Jay and Aaron:
- We have so much more to talk about, but high level he really thinks he can help out with architecture stuff (Path off of Oracle, ++), as well as strategize/check our plan on IT governance, IRDB nuances, CIO stuff. He’s gone through this before and seems happy to share what he’s learned to help smooth out the process.
- He reiterated how important the roadmapping work and product vision will be to package up to get buy-in and approvals from stakeholders. Given the turnover in NRM/CIO, the tighter the package and strategy, he said the opportunity to get what we need increases exponentially.
- He said there isn’t much he’s doing around NRM O&M right now, but he’s also available to help out with whatever we might need on that front if we have specific asks. Jay mentioned Jamie is more in the loop on that so just something to think about if/when we need to coordinate with the legacy team.

How we’ll bring him along/keep him in the loop:
- He’ll be joining this channel shortly! :yay2: (seeing if a direct invite link works, but will likely have to go through Slack admin)
I’ve added him to the weekly ship distro and sprint demo meetings.
- We’ll probably set up another sync in the next couple weeks to keep talking about collaboration with Jay. In the meantime, he’s open :ear::skin-tone-2: to talk through any of the Oracle dependencies, or architecture chat overall. He said feel free to invite him to any conversations we have around that.

**Comment by allisonnorman** [comment]
Aaron has been added to the Slack channel. We understand how to collaborate for now but still need to figure out other opportunities to involve him but that will evolve over the next few weeks. Closing this and will keep track of this via syncs with Jay.
