### ISSUE TITLE
Update wiki with workshop outcomes and high-level roadmap

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#116]
**Background**
As we are developing project artifacts in sprint 3 and preparing to share a draft RFQ for vendor feedback, we should check in to see what we can publish on the GH wiki. 

**We'll know we're done when...**
- [ ] We have added contemporaneous resources to the Wiki.

**Tasks**
- [ ] Product vision
- [ ] Refined problem statement
- [ ] Roadmap
- [ ] Design artifacts (TBD)
- [ ] Technical artifacts (TBD)

**Comment by allisonnorman** [comment]
Closing this issue because we're tracking adding artifacts to the wiki in relevant issues: #150, #39, #142, etc.
