### ISSUE TITLE
Draft research plan for usability test #1

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#117]
**Background**
As we narrow in and plan the prototyping work, we want to document our open research questions and identify what we don't know yet in order to form a research plan. 

**We'll know we're done when...**
- [x] We have a research plan for our next usability study, that captures key research questions that will inform prototype design and development.

Note: I think our scoping activities this week will help clarify the scope, but @MelissaBraxton mentioned that drafting research questions that we have today is something we could get started on now. 

**Tasks**
- [X] Draft design hypothesis/es
- [X] Write up research Qs
- [x] Prioritizing questions for research plan
- [x] Write interview protocol
  * [Interview protocol](https://docs.google.com/document/d/1_uxAhEIVcmBpVxNb-QoAQ9gOp7sc9gt_UNGQ7Crhvns/edit)
- [x] Create artifacts/probes for testing
  * We tested conceptual mocks of a dashboard that showed items someone needs to act on, their active agreements, and their pending agreements and modifications. The mock data was adjusted slightly based on participant's role:
     * [Program manager ](https://gsa.invisionapp.com/share/XT10L3LDUZJD#/448305145_Dashboard-1--pm--due)
     * [Grants specialist](https://gsa.invisionapp.com/share/P510L3L72TH6#/448307180_Dashboard-1--gm--due) 
     * [Budget approver](https://gsa.invisionapp.com/share/G610L5N8Q753#/screens/448322342_Dashboard-1--ba--due)
  * We also tested the current Django admin list view, search, and filters
- [x] a day or two before the first test, assess research Qs against artifacts /probes for testing
- [x] Refine research probes / research protocol until they're aligned

**Comment by MelissaBraxton** [comment]
Research plan is shaping up [here](https://docs.google.com/document/d/17NA19sNrWYfRevVI3FwLMePKidGoe4tbNA2dBqwgAuw/edit#)
