### ISSUE TITLE
Scope module 1

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#119]
**Background**
Based on the proposed module 1 user stories, let's get more granular about what module 1 will comprise, and what specifically is out of scope. 

**We'll know we're done when...**
- [x] We have a general sense of which features are in/out, that can be translated to a roadmap
- [x] We have a clear scope of what we will prototype in the E&I and where to begin

**Tasks**
- [x] Develop a framework for us to scope and estimate that includes draft user needs statements, journey map, and pain points to use as a tool for stakeholder alignment of what is a must and what can come later
- [x] Schedule a scoping session with Jay, Jamie, and Melanie to add in more detail and to make an initial cut line
- [x] Meet with Jay, Jamie, and Melanie to present concept and start generating ideas 
- [x] Synthesize and update based on feedback from Jay, Jamie, and Melanie
- [x] Discuss as a team and align on next prototyping priorities for E&I

**Comment by allisonnorman** [comment]
More scoping planned for sprint 4 in #150. Closing this issue.
