### ISSUE TITLE
Interview architects and devs

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#12]
**Background**
We've laid out what we hope to learn from these conversations [here](https://app.mural.co/t/gsa6/m/gsa6/1605566466024/b0d5b3e8e751df520a10d4ae4275ad6415740703?wid=0-1605633724707). This issue covers how we'll move from these high level ideas about what we need to learn to actual concrete conversations that give us the info we need.  

**Acceptance criteria** 
- [x] We have conducted interviews with relevant stakeholders 
- [x] Interview notes are anonymized and saved in shared drive

**Tasks**
- [x] Draft interview protocol including research Qs and interview Qs
- [x] Circulate draft for the team to review
- [x] Conduct interviews

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by neilmb** [comment]
Draft of the interview questions at https://docs.google.com/document/d/1MBfGkHjPBiZw5tSYD-Hb-kT4pHKq4qJbOnl2LS7MYT4
