### ISSUE TITLE
Meet with FS ISSO about platform choice and path to ATO

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#120]
**Background**

The new G&A application will be separate from the NRM suite of applications. The System Security Plan (SSP) for the current NRM suite will need to be re-written to exclude G&A and a new SSP made for the new application. We should start a conversation ASAP with our FS ISSO contact (Hieu.Nguyen@usda.gov) about what will make that new SSP/ATO easiest to get. Different platform choices can take very different amounts of work for security approvals. Using technologies that have already been used *at Forest Service* makes the process much easier.

This will impact our decision of what platform we use when we transition the prototype off of cloud.gov. Possible choices include the separate NRM rack in the USDA Kansas City data center, the CIO's Virtual Data Center (VDC) IaaS (https://www.ocio.usda.gov/products-services/data-center-services/infrastructure-service-iaas/virtual-data-center-openstack) and Forest Service's AWS platforms/accounts

**We'll know we're done when...**
- [ ] We have had a meeting with FS CIO security to talk about what makes things easiest for an ATO for G&A
- [ ] We have written down our understanding and know where we will be going to in June.

**Tasks**
- [ ] Schedule a meeting with Hieu Nguyen
- [ ] Schedule a meeting with Aaron Burk

**Comment by neilmb** [comment]
Meeting with Matt Reiss, the Cloud Architect at FS on Friday, March 19th to hear about where they are on getting ready for AWS and if they will be ready for us to go there in May/June.

**Comment by neilmb** [comment]
I will wait to schedule the ISSO meeting until after we have more clarity on the platform that we'll be using.

**Comment by neilmb** [comment]
From a meeting with Matt Reiss and Aaron Burk: We can target the same AWS environment that OpenForest was moving to. Matt Reiss can get us a dev instance there after 4/30/21 when the OpenForest move is complete.

From a meeting this morning with our FS ISSO Hieu Nguyen and Aaron Burk:
- The FS AWS environment is called Skynet
- Skynet is ATOed already so modernizing G&A onto that platform doesn’t need a separate ATO.
- Skynet is operated by the USFS so it doesn’t even need an Interconnection Security Agreement (ISA) for the connection between Skynet and NRM. We just have to send a paragraph of documentation that the connection exists.
- When we are ready to connect up to the NRM databases in staging and production Skynet environments, then we may need to update the Privacy Threshold Analysis (PTA) and Privacy Impact Assessment (PIA) because we will be accessing PII.
