### ISSUE TITLE
Draft roadmap for module 1

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#123]
**Background**
Based on our scoping exercise (#119), we translate this into a roadmap that we can begin executing on, and that helps set up the plan for the vendor.

**We'll know we're done when...**
- [x] We have alignment on prioritized list of epics (what's in/out of scope for an MVP) - #119 
- [x] We have translated that list of epics into a roadmap format that we can begin executing on. 

**Tasks**
- [X] Leverage scoping activity output + draft RFQ user stories
- [X] Reference previous USFS/18F roadmaps and framing docs for organizational consistency, as feasible (see below)
- [X] Review concepts and examples with Jay in 1:1
- [x] Draft module assumptions, risks, key features, etc. ([Draft doc](https://docs.google.com/document/d/1s8TwI5bfuhLAEVgs4VAc6g-yPWnGQAh59CaztU7jst0/edit#))
- [x]  Refine based on #119

**Comment by allisonnorman** [comment]
Created #150 to continue refining roadmap.
