### ISSUE TITLE
Break out demo from planning

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#124]
**Background**
We want to pull out demo from the planning meeting so we can have the opportunity to invite stakeholders. 

**We'll know we're done when...**
- [x] We've scheduled a demo meeting. 

**Tasks**
- [x] Talk to the team about this and align on duration and scheduling.
- [x] Update gcal invites.
