### ISSUE TITLE
Refine prototype based on user research findings

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/NRM-Grants-Agreements#131]
**Background**
Based on the usability tests in sprint 3, and the synthesis/insights (#142), we will want to refine the prototype based on user research findings. 

Also, following up to #114, the tasks below include some small tweaks to the admin interface to better use USWDS. 

**We'll know we're done when...**
- [ ] Tasks outlined below are complete 

**Tasks**
- [ ] paginator colors are wrong. Can we uswds-ify it, or at least get the colors right?
- [ ] What is the difficulty of changing icons over to USWDS versions? Are they available?
- [ ] TBD - additional stories

**Comment by tbaxter-18f** [comment]
@allisonnorman I doubt we'll start this during this sprint. I just wanted to have it logged so we could capture things as they appear.

**Comment by allisonnorman** [comment]
Let's refine in a meeting to talk about how much fidelity to incorporate in revisions, how much farther we take this.

**Comment by allisonnorman** [comment]
Closing this as stale. I added the tweaks to #190 to make sure we don't lose those.
