### ISSUE TITLE
Admin UI tweaks for usability tests

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#137]
**Background**
Before we show the admin UI to users during next week's tests, we want to make a few tweaks to reflect user research to date. 

**We'll know we're done when...**
~- [ ] Global action to "delete" rows has been removed~
- [x] Columns reflect the order in the task below
- [x] Columns not listed below are not shown

**Tasks**
- [x] Replace columns currently shown with the following columns in this order: 

- agreement # 
- project title
- cooperator name
~- total amount~
- agreement effective date
- expiration date

- [x] In the "filter" box, include all of the statuses that we have in the BD, if they're not there already.

**Comment by MelissaBraxton** [comment]
@cmajel  - In your chat w/ Jamie, did you get any hints on where in the DB we could look for "total amount"?

**Comment by tbaxter-18f** [comment]
Total amount (and all the useful dollar fields) appear to be in a table or system we haven't seen yet.

**Comment by MelissaBraxton** [comment]
Got it! I think we can just leave that off for next week. I'll update the issue.

**Comment by tbaxter-18f** [comment]
Also (and should I be adding these comments in figma or something?) Since the first item is the link to the detail view, it looks weird to me to have the agreement number be that link rather than the Name. So I'd suggest name then agreement number.

**Comment by MelissaBraxton** [comment]
I think here's a fine place for the chat! Are you saying the column order seems weird or it's weird that the detail  view is a link from the agreement number. 🤔

**Comment by tbaxter-18f** [comment]
Both. Since the name is the primary data piece and much more scannable, it feels more right going first. I've flipped it back and forth a dozen times and it's always weird to me with the inscrutable number first.

@cmajel did you capture from our meeting which fields best represent those dates?

**Comment by tbaxter-18f** [comment]
![Screen Shot 2021-03-19 at 3 04 12 PM](https://user-images.githubusercontent.com/32077682/111836531-71d9d180-88c4-11eb-8e47-a1a716337ef0.png)
![Screen Shot 2021-03-19 at 3 03 52 PM](https://user-images.githubusercontent.com/32077682/111836533-72726800-88c4-11eb-844b-49ae5f847341.png)

**Comment by MelissaBraxton** [comment]
Let's try it your way, and we can find out more about how folks scan when we talk to them next week!

**Comment by tbaxter-18f** [comment]
Unrelated, but I also wondered if people scan for cooperator to find agreement number, if the better answer is to have a "agreements for cooperator" list.

**Comment by cmajel** [comment]
@tbaxter-18f, for dates here's what I'm thinking:

agreement effective date
* I feel like `proj_start_dt`,aka the date that cooperators are able to charge back to, makes more sense than `proj_execution_dt`, aka the date the agreement is awarded.  But, I don't really know. Let's try start date and see how it goes during testing. 
* Let's also change the label to `Start date`

expiration date = `proj_expiration_dt`

Re finding agreement numbers via cooperator, a list of agreements by cooperator feels like an interesting search task.

**Comment by tbaxter-18f** [comment]
Just to be sure I'm clear, proj_start_dt is the only date we want for testing this week?

**Comment by cmajel** [comment]
Start date and expiration date for this week is what I'm thinking.

**Comment by tbaxter-18f** [comment]
Separate columns or stacked in a list? The former makes it easier to sort by. The latter works better when screen space gets tight.

**Comment by MelissaBraxton** [comment]
My hunch is that separate columns will be more usable.

**Comment by tbaxter-18f** [comment]
Out for review now: https://github.com/18F/NRM-Grants-Agreements/pull/138

Screen shot from my local machine:

![Screen Shot 2021-03-22 at 10 10 14 AM](https://user-images.githubusercontent.com/32077682/112012163-f744c800-8af6-11eb-9517-ac296755f82d.png)
