### ISSUE TITLE
Save record functionality

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/NRM-Grants-Agreements#139]
**Background**
While Django's admin gives the ability to save new objects out-of-the-box, our data models have a lot of hidden and generated fields. We need to test and ensure that when a new object is created, all fields are populated correctly. In addition, we have a number of fields that are required by the system or policy but may not have a technical requirement. We need to be sure those are covered, too. 

**We'll know we're done when...**
- [ ] We can save a new object with no errors.
- [ ] All fields on the record that have generated values are being populated with valid values.
- [ ] We have consulted with the spreadsheet of system-required fields and ensured those fields are properly populated.

**Tasks**
- [ ] 
- [ ]

**Comment by allisonnorman** [comment]
Thanks @tbaxter-18f! Sorry I missed it and thank you for creating it! I combined the two, perhaps at the expense of being a bit redundant. I'll close this one and we can use #154
