### ISSUE TITLE
Get list of potential users and stakeholders to interview

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#14]
**Background**
We need to start with a list provided by the agency of folks we will talk to. 

**Acceptance criteria** 
- [x] List includes a min. of 5 grants specialists
- [x] List includes devs and architects on the current team
- [x] List includes IT services acq CO and contract specialist(s) 

**Tasks**
- [x] Ask for list from point of contact
- [x] Review list for completeness 

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Chatted with Jennie who is working on getting us a list on Monday 11/30.

**Comment by MelissaBraxton** [comment]
Moving to waiting - We'll ask about external G&A users when we meet with Grants specialists hopefully next week. Miatta is waiting on a response re: the CO.
