### ISSUE TITLE
Write up and share usability test insights 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#142]
**Background**

**We'll know we're done when...**
- [x] insights are documented in wiki
- [x] refinements are documented as user stories 

**Tasks**
- [x] Synthesize
- [x] Write up
- [x] Get one other person on team to review
- [x] Post to wiki
- [x] Add user stories to user story sheet (for #166)

**Comment by allisonnorman** [comment]
Posted to wiki: https://github.com/18F/NRM-Grants-Agreements/wiki/User-research-topline-----Sprint-3,-March-2021

**Comment by allisonnorman** [comment]
Jay is planning to finish this today. I'm going to remove the task of adding these to Github as that's captured in #166.

**Comment by allisonnorman** [comment]
@MelissaBraxton Jay and I finished refining some of the larger stories, but this list is not exhaustive. The more specific stories can be found in the [research report version with comments.](https://docs.google.com/document/d/1ZlREp24fQ78CoawvK5XxlWbOyzsJLm3AyEBJcQ89WH4/edit#heading=h.g2c0bszh8eun). 

After talking with Jay, I think we need to hold off adding these to GH just yet. I added them to the [user story sheet](https://docs.google.com/spreadsheets/d/1_uhFjs-SaQztfjPYIJ5o6-0AXnJU05AdGzTBcs5U7ak/edit#gid=0), which I can revisit as part of overall framing (which stories do we need to add in for roadmapping purposes), as well as #166 in the backlog. 

Are we good from your perspective to close this out?
