### ISSUE TITLE
Push app to cloud.gov automatically after merge to main branch

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#144]
**Background**

Up to know, when we merge code changes in a pull request, we have to then manually run a command on our laptop to deploy that code to cloud.gov. We should set up an automation step so that after a merge to the main branch happens, then the code is automatically pushed to cloud.gov.

This should be possible by adding a new job to our CircleCI setup that runs `cf push --strategy=rolling`. We will have to figure out how to store the credential information on CircleCI to allow that push to happen.

**We'll know we're done when...**
- [x] A PR that is merged to main results in the new code being deployed to cloud.gov

**Tasks**
- [x] Figure out how to store cloud.gov access credentials on CircleCI to allow the push to happen
- [x] Install the cloudfoundry utilities to our CircleCI image.
- [x] Configure the CircleCI job to push only when merges have happened to main

**Comment by neilmb** [comment]
Cloud.gov's documentation for this is here https://cloud.gov/docs/management/continuous-deployment/
