### ISSUE TITLE
Meet with USDA Grants officer

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#146]
**Background**
Based on recent conversations with QSMO, we want to connect with the USDA Grants team. We are using QSMO to make that introduction.

**We'll know we're done when...**
- [ ] We've met with a USDA grants lead and connect their priorities to this project. 
- [ ] 

**Tasks**
- [ ] Get introduction from Andrea
- [ ] Set up meeting
- [ ] Meet
