### ISSUE TITLE
Try to gather cost information on Oracle 12 August '22 support change

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#147]
**Background**

In August 2022, Oracle's Fusion Middleware version 12 will move from Premier support to Extended Support. This motivates  the urgent modernization effort for G&A that is the motivation for this engagement. It would be good for us to know just how costly the change in that level of support will be. The more it costs, the more urgent it is to prioritize speed over features for the new app.

This is helpful information for our prioritization exercise, but we should time box this effort so we don't spend too long digging for this info, or ruffle too many feathers with our questioning.

**We'll know we're done when...**
- [ ] We have some estimate however vague for the additional cost associated with keeping Oracle 12 past August 2022

**Tasks**
- [ ] Ask on Slack if anyone knows anything about this
- [ ] Ask Steve Lammey on FS Teams if he has any information on this

**Comment by allisonnorman** [comment]
Include graph into path off of Oracle doc

**Comment by neilmb** [comment]
Added the information that timber permitting found into https://docs.google.com/document/d/1EMJCN-Z0703JPdk6RvQFcfIl6RBX6oxYsJfU3-SlilQ/edit#heading=h.790tt73ijnx9
