### ISSUE TITLE
Review technical documentation

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#15]
**Background**
Reviewing technical docs will help us reach our goal of understanding the technical landscape. 

**Acceptance criteria** 
- [x] We've documented insights in a shared location
- [x] We've documented any remaining knowledge gaps
- [x] Plans for how we'll fill knowledge gaps are documented as new issues

**Tasks**
- [x] Melissa tracks down who can get us this info
Get and review
- [x] Get a list of available platforms from Pega
- [x] a list of applications, middleware, database, API etc. 
- [x] list of third party services from IT contact, any end of life s/w and h/w. 
- [x] G&A and NRM architecture diagrams
- [x] any documentation of the current ATO process

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by neilmb** [comment]
We learned a bit from Pega about their platform, but nothing else from them. I'm going to mark this as done with our technical solutions document and design documentation so far.
