### ISSUE TITLE
Refine roadmap

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#150]
**Background**
Building off of work in #119 and #123, and related to overall product framing goals in #39, we want to continue to refine the roadmap and get it to a shareable state for stakeholder feedback. 

**We'll know we're done when...**
- [x] We have aligned on what we know today, and the roadmap reflects our current thinking in as much detail as possible without being overly prescriptive.  
- [X] We have a shareable roadmap (even via framing docs) for stakeholders, and linked to it on the wiki. (Related #39, also will further socialize in #199)

**Tasks**
- [x] Estimate timeline for M1 and revisit the cut line: how could we more thinly slice the work and what could wait until M2/M3. 
- [x] Dig into some of the areas we need to think more about based on what we've learned (boxes with border on roadmap)
- [X] Finalize module assumptions, risks, key features, etc. (from [draft doc](https://docs.google.com/document/d/1s8TwI5bfuhLAEVgs4VAc6g-yPWnGQAh59CaztU7jst0/edit#)) and add to roadmap.
- [X] Publish to wiki.

**Comment by allisonnorman** [comment]
[Roadmap framing doc draft](https://docs.google.com/document/d/1k-lgrzYcLBtq4uSNirK5Umh5prYGUvglhp7ni_NdkZE/edit#heading=h.tim51i3wpy2m)

**Comment by allisonnorman** [comment]
Mural: https://app.mural.co/t/gsa6/m/gsa6/1616102462523/caae527dbaa5eed61a517b0c5039b7541c667da2
Roadmap narrative on wiki: https://github.com/18F/NRM-Grants-Agreements/wiki/Product-roadmap
