### ISSUE TITLE
Submit a form that writes to the sandbox db

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#154]
**Background**
We are exploring opportunities to de-risk electronic agreement creation by doing some prototyping work in our E&I. More details can be found in #152 around how this fits into a broader strategy of de-risking, and more detailed user stories to come.

We have an assumption that using a new online agreement form to create a new record in the DB will be easy, and our goal is to validate that. #153 covers mocking up a new agreement creation form. Based on the mocks, we should think and implement a form submission that could write to our sandbox DB. 

Note from Carter: While Django's admin gives the ability to save new objects out-of-the-box, our data models have a lot of hidden and generated fields. We need to test and ensure that when a new object is created, all fields are populated correctly. In addition, we have a number of fields that are required by the system or policy but may not have a technical requirement. We need to be sure those are covered, too.

**We'll know we're done when...**
We have validated that we can write to the db when a form is submitted, including:
- [ ] We can save an object with no errors. 
- [ ] All fields on the record that have generated values are being populated with valid values.
- [ ] Custom Django Form and/or save() methods are created to capture non-editable fields (such as created_by)
- [ ] Both Required AND Mandatory fields are captured.
- [ ] We have consulted with the spreadsheet of system-required fields and ensured those fields are properly populated.
- [ ] We have implemented whatever interactive components are necessary (based on #152) for user testing. 

**Tasks**
- [ ] 
- [ ]

**Comment by tbaxter-18f** [comment]
I think this and 139 overlap a lot, so we could close one. 

I'd like to not wait for mocks, and instead approach this as verification/validation that we can save a record accurately.
