### ISSUE TITLE
Analyze user help desk ticket data

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#16]
**Background**
Just one other data source for helping us understand users and pain points. 

**Acceptance criteria** 
- [x] We've documented insights from reviewing help desk ticket data including common pain points and user frustrations

**Tasks**
- [x] Ask for export of help desk ticket data
- [x] Analyze data and identify patterns
- [x] Write up insights and share with the team

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Data file is [here](https://docs.google.com/spreadsheets/d/13O1Ew2OqwP3fqiR5GxdeIV1uEdXM6lom/edit?rtpof=true#gid=1697821099)
