### ISSUE TITLE
Draft transition plan

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#161]
**Background**
We want to start drafting a transition plan to outline what long-term success looks like both as we:
- Think about preparing to onboard a vendor
- Plan for 18F rolling off in August

This will help us understand what we can start doing now to ensure that FS POs have the experience they need to successfully manage a vendor team in the near-future. 

Note: This plan will not be set in stone, and will evolve as we learn more about the acquisition strategy. We can start with what we see now, and evolve it into a more formal transition plan as the acq strategy gets solidified. 

**We'll know we're done when...**
- [x] We have a draft that will steer conversations about what continuing success looks like on this project post-August, and some alignment on what activities we could start doing now in pursuit of those goals. 

**Tasks**
- [x] Outline transition plan doc (use Open Forest plan as a shell?)
- [X] Circulate to team for review
- [x] Revise based on feedback

Resources we talked about referencing or including:
- Heuristics doc
- Acceptance/tech lead doc from Laura G (code quality proxy measures)
- Open Forest transition plan

**Comment by neilmb** [comment]
One component of this plan could be a wiki-facing version of a "README" that helps an incoming vendor team to get up to speed on our roadmap, product vision, technical choices, etc.

We also need "how we work" documents so that an incoming vendor team knows how the Product Owner gets included in their sprint processes and how things get approved.

**Comment by neilmb** [comment]
Hundreds of transition plans linked here https://docs.google.com/document/d/1SuwO9K3135yMz3mYWDTiyPLItXjooMffRgd6LXrJi6s and OpenForest’s plan https://docs.google.com/document/d/1JsGH_7OkDMZhi6xOW0xVeCkNO8aLgUTIUpRLlnsERxk

And a template version https://docs.google.com/document/d/11CnuzS5zLZsdS2Ox1P7S2h4j5oj4et_B0DYY_Z6G90U

**Comment by MelissaBraxton** [comment]
Draft plan is [here](https://docs.google.com/document/d/1YOlrpQXbbWwYcE-LYeqoavvMDolHjIgBmfQorp8Ft3c/edit)
