### ISSUE TITLE
As-is workflow model for pre-award processes

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#162]
**Background**

**We'll know we're done when...**
- [x] We have a workflow model that depicts pre-award processes from proposal creation to fully executed agreement
- [x] Workflow model is in a notation that can be extended to include post-award process down the road if need be

**Tasks**
- [x] Draft model
- [x] Review w/ internal 18F team
- [x] Cognitive walkthrough w/ SMEs
- [x] Refine based on feedback

**Comment by MelissaBraxton** [comment]
@cmajel and @tbaxter-18f - Draft model is [here](https://app.mural.co/t/gsa6/m/gsa6/1617302710083/284af01bd7dec812ac7013275a7767d1a99693ee)

**Comment by MelissaBraxton** [comment]
Waiting on walkthrough scheduled for Wed. 4/21.
