### ISSUE TITLE
Develop a success metrics framework with FS POs

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#165]
**Background**
We want to align on success metrics for how the FS team can set goals and measure them to determine how a particular feature or set of features impacts overall KPIs. This includes both performance related goals (_Time to complete an agreement will decrease_), as well as devops goals (_There will be more frequent deployments_).

[Here's a scratchpad](https://docs.google.com/document/d/1vZ7ebGcZv6vsZcDlWs0EAElV0AF16HPhtmoqGb7vsSg/edit#heading=h.a812apir3gdn) with some initial thoughts around module 1 success metrics.

**We'll know we're done when...**
- [ ] We have developed a set of KPIs and have alignment with stakeholders 
- [ ] We've determine how to measure baseline for these metrics, and have stories in the backlog that articulate the performance indicators

**Tasks**
- [ ] Create a framework for discussion
- [ ] Workshop with POs
- [ ] Once determined, create a new issue for measuring the baseline for these metrics (what is the # currently?)
