### ISSUE TITLE
Add epics and user stories from RFQ to backlog

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#166]
**Background**
Let's add the epics and user stories from the RFQ to the backlog. These are prone to change as we learn more, but it will be helpful to have them in a centralized place that we can update as needed.

**We'll know we're done when...**
- [ ] The backlog reflects the epics and user stories from the draft RFQ
- [ ] We have internal alignment on how we'll update and add more stories as we learn more. 
- [ ] Jay is comfortable adding and editing issues. 

**Tasks**
- [ ] Figure out how to best use GH projects for epics + milestones, as well as where to note them as true backlog items (label: vendor?)
- [ ] Create epics and user story issues with Jay.
