### ISSUE TITLE
As a budget approver, I need a direct path to approve a commitment from a new proposal or modification when an action is required by me. 

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#169]
**Notes**
<goals of our prototyping, how deep we want to go here, how much we want to de-risk (tying data to a person and action)>

**We'll know we're done when...**
- [ ] PO approval + acceptance
- [ ] 

**Supporting documentation**
- [ ] <Link to the research document>

**Open questions**
- [ ] Before we prototype the proposal creation workflow, is there a way for us to understand who an approver is (based on the current data)? 
- [ ] What steps/data in the database helps us know when a commitment approval is pending? 

**Tasks**
- [ ] Determine what tasks are necessary to complete this issue. 
- [ ] Usability test

**Comment by allisonnorman** [comment]
In ZH, we can use this to summarize the` signal review and route to the next step` epic and close the issue. Keeping this until we switch over.

**Comment by tbaxter-18f** [comment]
I think this will be blocked on #252 (assignment)
