### ISSUE TITLE
Brief Jamie and figure out a plan to keep her more in the loop

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#175]
**Background**
Based on feedback from Jay, we need to figure out how to involve Jamie into our prototyping work, both so she knows what we are focusing on now as well as helping her prepare to work with a future vendor. We want her to be involved as possible but also want to be mindful of how to involve her into our practices in a meaningful way (e.g. not just dumping her into all of our meetings if she doesn't have the time) 

**We'll know we're done when...**
- [ ] We have briefed Jamie and she knows what our goals are for the E&I (de-risking strategy)
- [ ] We've aligned on ways of involving her so that she knows what we are working on and can weigh in as a SME as needed.

**Tasks**
- [ ] Set up meeting to sync with Jamie (separate meeting or a strategy session?)
- [ ] Share roadmap and briefing docs when ready
- [ ] Add Jamie to Slack channel

**Comment by allisonnorman** [comment]
Folding this into #199
