### ISSUE TITLE
As a Grants Specialist, I need to know which agreements are out of compliance, so that I know how to prioritize my time

### ISSUE THREAD

**Issue by Jrbergjr** [18F/NRM-Grants-Agreements#178]
**Notes**

**We'll know we're done when...**
- [ ] A GMS is in the system and can view agreements quickly that are out of compliance

**Supporting documentation**
- [ ] 

**Open questions**
- [ ] This question needs more vetting.  what are we using as "out of compliance"?  Overdue reports, invoices, expired not closed?  Or other more difficult compliance issues - FATTA reporting, other policy compliance issues...

**Tasks**
- [ ] Work with Melanie and Jamie to gain insight on what is out of compliance.
- [ ] Vet a few GMS to further clarify what they need to see for out of compliance agreements

**Comment by tbaxter-18f** [comment]
@allisonnorman IMO we need a few things to do this...
1.  A story leading up to this to answer the open question.
2. Role configuration (so we know you're a grants specialist and to show you)
3.  the engineering work to check against the out-of-compliance things to highlight them

And do we show ALL out of compliance, or just ones assigned to you?
