### ISSUE TITLE
Document tradeoffs of eFG, NRM, or building a system.

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#18]
**Background**
We want to lay out cost tradeoffs of staying in NRM, transitioning to eFG at the USDA level, transitioning to FS-version of eFG, or building a new system. 

**Acceptance criteria** 
- [x] The comparison includes criteria that are relevant to our stakeholders
- [x] Includes a quad chart snapshot of each option for leadership
- [x] Documentation is findable to our 18F team but not public

**Tasks**
- [x] Determine criteria relevant to our stakeholders that we want to base our comparison on
- [x] Write up trade-offs
- [x] Circulate to the team for review

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by donnykwan** [comment]
Would this also be part of the SWOT?

**Comment by MelissaBraxton** [comment]
Yes, my thinking is that this IS the SWOT.

**Comment by MelissaBraxton** [comment]
Even if they go with a vendor and proprietary software, they will need a product owner. Not having one incurs major risks. A dedicated product owner is in part of the cost no matter which option you chose.
