### ISSUE TITLE
Investigate WorkPlan linking at agreement creation time

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#185]
**Background**

Current policy is that every grant/agreement needs to be linked to a "work plan" in the FS budgeting system called WorkPlan. It appears that this link is done by just including an ID number from the WorkPlan application when the agreement is created. There is some additional information with amounts and dates that is exchanged with WorkPlan but we don't know exactly how.

We should research the WorkPlan integration and figure out how we would handle it in our proposal creation flow.

**We'll know we're done when...**
- [ ] We can include WorkPlan appropriately in our proposal creation flow 

**Tasks**
- [ ] Review the existing NRM code to find out how WorkPlan integration happens 
- [ ] Talk with Jay/Jamie to verify our understanding of how WorkPlan is integrated
- [ ] Import any needed tables from the database, or figure out that we don't need to

**Comment by MelissaBraxton** [comment]
Two Qs re: workplan data: 

- Data on the budget approver who approves workplan will be useful in the agreement creation workflow. Can we use it?
- Workplan has a field for "FS contact" that could also be user. What does this look like in workplan? Who enters it? What role is the contact typically, how "good" is the data? Can we use it to direct approved workplans to people's individualized dashboards?

**Comment by neilmb** [comment]
From Allison: Are we sure that Workplan is only one directional? Jamie mentioned something about data coming from NRM that ASC didn't like which made me think there might be a two way data flow (I also could have misunderstood!)

**Comment by neilmb** [comment]
Jay said today that info from NRM can overwrite what is in WorkPlan and upset the budget folks. We have also heard that info comes in from WorkPlan to start an agreement, so there is definitely a bi-directional flow of information here (but the two sides may be sequential).

**Comment by tbaxter-18f** [comment]
From what I've seen and heard, we should probably give this some priority. I believe (from usability research) it would likely pretty helpful to capture the workplan pretty early on, rather than late in the process. This would let us prepopulate a bunch of fields and reduce the creation burden, and I think it would be easier to capture errors/mismatches.

There's also a BIG question about whether or not that bidirectional flow of data is desirable, since the two systems are overriding one another. It may be prudent to make the flow one-way, have the fields read-only, and say "if you want to change, this do it over here". 

I can also see some desire to move the workplan creation out of the legacy app, but that discussion hasn't happened yet, so I don't know.

Almost definitely blocked on #187
