### ISSUE TITLE
Talk to budget about Workplan's future

### ISSUE THREAD

**Issue by cmajel** [18F/NRM-Grants-Agreements#187]
**Background**
Workplan is the system that budget approvers use to track and report budgeting tasks for their teams. The G&A application currently links up agreement records with Workplan records so that they can share project and funding details. We want to make sure a new G&A application can integrate with systems that it will need to consume or share data.

We want to talk with someone from the budget office to understand Workplan's future, and if the team is planning a transition to a new system that may affect our work.

**We'll know we're done when...**
- [ ] We know if a Workplan integration will be needed with a new system, or if we need to plan for another integration
- [ ] ???

**Tasks**
- [ ] Jay identifies who we need to talk to
- [ ] We meet with them
- [ ] Conversation is documented

**Open questions**
- Should we also document what a budgeting system needs to share / consume from an agreements system?

**Comment by cmajel** [comment]
@cmajel to reform as a research spike. [Some questions here ](https://docs.google.com/document/d/1_OF7ZC4O6VAMh9hxWLktRgjiFcSeMqwUBkOZcwWG-P4/edit#)for coworking tomorrow.

**Comment by MelissaBraxton** [comment]
Some overarching Qs: What need does linking workplan to G&A serve? Who has this need? Are there alternative ways we can meet their need if we decide not to integrate workplan with the new system?

**Comment by tbaxter-18f** [comment]
I think given the related #185, we have a fairly high-priority need to determine.

1. Is bringing in data from a workplan desirable?
2. If not, then we can close #185 as wontfix
3. If so, proceed with #185?

It seems like we have some conflictiing views on whether or not it's helpful that we need to resolve.

From a data/engineering standpoint, it CAN let us prepopulate some fields, but I'm not sure that's actually all that helpful to users, especially given the overwrite issues with workplans.
