### ISSUE TITLE
Review Deloitte report & G&A strategy doc

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#19]
**Background**
G&A has tried to solve this problem before they worked with Deloitte on a strategy that never went anywhere. We want to avoid those same pitfalls. 

**Acceptance criteria** 
- [x] Insights are documented in a findable but not public place

**Tasks**
- [x] Melissa emails Chris to get access to Deloitte report and G&A strategy 
- [X] Mel reviews report
- [x] Donny reviews report
- [x] Neil reviews report
- [x] Document insights and open Qs

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Chris sent us the G&A strategy but did not share work of any previous consultants. A draft of the G&A strategy doc is [here](https://docs.google.com/document/d/1e9NsONHRw5B72SP9ZBWlENhPSyMXv8slVWgYw8BZnpA/edit#heading=h.1fob9te).

**Comment by neilmb** [comment]
I read and left observations at the top of our copy of the doc.
