### ISSUE TITLE
Create a to-be architectural diagram

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#196]
**Background**
Both from a framing, planning, and governance perspective, we'd like to document our thoughts on a to-be architectural state. Though this could be prone to change, we want to lay out the architecture of a new G&A application. 

Ideally, once done this could be further sliced to help inform architectural milestones within the three vendor modules. This could be done after the fact and I can help with this!

The first audience  this will be the FS CIO Operations and Service Delivery (OSD) group who will use it to set up the cloud infrastructure.  A second audience would be a future vendor team.

**We'll know we're done when...**
- [ ] This is published on the project wiki. 

**Tasks**
- [x] Draw the to-be diagram as a Google Drawing
- [x] Get review from the team on it

**Comment by neilmb** [comment]
https://docs.google.com/drawings/d/135bDMm1yFtVDXiimWcI91NIsUV5mHiIZi6tdihqIidU/edit is probably our most complete expression of what we know so far for the Module 1 system.

**Comment by neilmb** [comment]
https://docs.google.com/drawings/d/1h5aXlHILnFiQlrX8nLEWqiQpQ2XKKGJIKzfLhTgD2Rw/edit is a simplified version that we used with the FS OSD group.

**Comment by allisonnorman** [comment]
@neilmb 
![Screen Shot 2021-04-26 at 1 49 08 PM](https://user-images.githubusercontent.com/6900926/116149180-ae080b00-a696-11eb-89b4-0558978323b2.png) I'm planning on uploading this to our wiki, and actually needed to create a comment here in order to generate an easy URL. Is there any other language or context you'd like to include on that page?

**Comment by neilmb** [comment]
I added some text to that page and added it to the sidebar.
