### ISSUE TITLE
Onboard Neil

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#2]
**Acceptance criteria** 
- [x] Neil has access to all tools and info he needs
- [x] Neil has read enough background material to feel confident getting started on the project

**Tasks**
- [x] Review NRM technical PA final reports
- [x] Review project scope doc
- [x] Review Timber Permitting README
- [x] Review Timber permitting Path Analysis report
- [x] Neil has been added to the GH G&A team 
- [x] Neil has been added to all relevant Slack channels
- [x] Credentialing process has begun

**Definition of done**
- [x]  Meets acceptance criteria
