### ISSUE TITLE
Draft deck for first weekly check in on 11/25

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#20]
**Background**

**Acceptance criteria** 
- [ ] Everyone is comfortable w/ what we plan to share with folks at the 11/25 mtg

**Tasks**
- [ ] Melissa Drafts deck
- [ ] Circulates for team to review
- [ ] Incorporate team feedback
