### ISSUE TITLE
Research eAuth integration available in Skynet

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#203]
**Background**

Matt Reiss mentioned in a meeting that they have eAuth integration set up in Skynet/AWS. Since we will need that integration for module 1, we should learn more from FS on how that is set up and how we can make use of it.

**We'll know we're done when...**
- [ ] We can write a description of how we will get eAuth integration working on our Skynet platform

**Tasks**
- [ ] Set up a meeting with Matt Reiss to learn more about what they have done with eAuth
- [ ] Research eAuth integration documentation from USDA

**Comment by neilmb** [comment]
Talk to Matt Reiss and Shadat Mahmud shadat.mahmud@usda.gov from the FS Cloud Foundation team for technical information on this.

**Comment by tbaxter-18f** [comment]
We'll need to figure out if eAuth will tell us the user role (and if so how we'll work with that in our system) or if an admin will have to manually assign users to roles and groups.

**Comment by neilmb** [comment]
Here is the eAuth integration developer documentation for EAD's FS-Apps integration service: https://code.fs.usda.gov/EAD/FS-Apps/files/2129/DRAFTv5_FS_APPS.docx

An important item in there is that it only supports server-side applications. That is, their service only appears to support OAuth2's "Authorization Code Grant" (http://www.bubblecode.net/en/2016/01/22/understanding-oauth2/#Authorization_Code_Grant) rather than the client-side "Implicit Grant".

**Comment by beechnut** [comment]
Happy to report that, in a meeting just now, Matt Reiss said that eAuth is ready for client-side application use.

@AdamUSDA also indicated he's been thinking about how authorization will work. Let's definitely bring this up at sprint planning this week (Aug 11) and figure out what we want to do here this sprint.

**Comment by AdamUSDA** [comment]
Hey @neilmb 

The Mulesoft team is looking at eAUTH as well. I'm not certain if that has been implemented or not. Casey sent this to me as a possible usage.

https://apisero.medium.com/mule-oauth-provider-da7ac785520c

**Comment by AdamUSDA** [comment]
@neilmb I talked with the CIO team and we talked about the eAuth process. After that discussion I think that using the eAuth service that they have put in place will be our best option for now.
