### ISSUE TITLE
Research email notification service

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#206]
**Background**

The current system sends lots of notification emails. Sending emails can be complicated service to set up, so we should investigate how we plan to do this in module 1. Is there an existing service inside of NRM that we can use? Is there something provided in Skynet/AWS that we could use instead? Is there a USDA shared service that we could leverage?

**We'll know we're done when...**
- [ ] We document on this ticket what our plan is for sending email notifications.

**Tasks**
- [ ] Ask Jamie how the existing system sends emails
- [ ] Ask Matt Reiss if there is a USDA integration for sending emails in Skynet or what AWS services they can access

**Comment by tbaxter-18f** [comment]
If we want email notifications, this a must-do first step.
