### ISSUE TITLE
Research SAM.gov integration

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#208]
**Background**

NRMs Contacts service contains information about many cooperators. Many of them need to have accounts on SAM.gov and the information in NRM needs to match what is on SAM.gov. We could simplify the system greatly if we could interface with SAM.gov and make use of their contact information directly.

**We'll know we're done when...**
- [ ] We can document on this ticket how we will integrate with SAM.gov and how it will help FS to simplify their contacts management process. (Probably need a separate document describing this.)

**Tasks**
- [ ] Look at documentation on what sort of data integration is available from SAM.gov
- [ ] Talk to Jamie to clarify requirements on cooperators and who needs to be in SAM.gov and what must match between the two systems.

**Comment by tbaxter-18f** [comment]
This is probably closely related to #225 and #200
