### ISSUE TITLE
Plan mid-point check in mtg

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#21]
**Background**
We want to check in midway through the project to bring our partners along in what we're learning. Aiming for a 90 minute mtg.

**Acceptance criteria** 
- [x] Deck includes insights from research to date
- [x] presentation can be delivered in 60 minutes leaving ample time for discussion/Qs

**Tasks**
- [x] draft workshop goals
- [x] draft attendee list based on goals
- [x] draft deck
- [x] circulate for team to review
- [x] incorporate feedback

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
We can draw some material from[ this](https://docs.google.com/presentation/d/1bSnIv3IbDylYl6c65otB7Mdb59on7jBFckZ7niYOBlM/edit#slide=id.g5f57310182_0_448).

**Comment by MelissaBraxton** [comment]
Workshop planning doc draft is [here](https://docs.google.com/document/d/1aw7M_k19R-ubRDb4OCV7V-ZpPfnOK0uO8njxoyYG6dk/edit?usp=sharing)

Topics to consider, depending on workshop goals: 
- [ ] a modular acquisition approach
- [ ] encapsulation strategy
- [ ] agile product roadmaps
- [ ] human centered design
