### ISSUE TITLE
Overview of Federal Acquisition for 18F Team

### ISSUE THREAD

**Issue by Miatta18F** [18F/NRM-Grants-Agreements#25]
**Background**
Miatta will present an overview of Federal Acquisition as it applies to this engagement.

**Acceptance criteria** 
- [x] Miatta presents info to team

**Tasks**
- [x] A deck is created 

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by neilmb** [comment]
@Miatta18F Can you put a link to your deck in a comment here on this ticket?

**Comment by Miatta18F** [comment]
Here it is! https://docs.google.com/presentation/d/1FjJWwXrTbXexdTGeZKP6OjQ8i5B3GmOAj5MQTF_arLg/edit#slide=id.g4eb21fd7af_0_178
