### ISSUE TITLE
Shchedule mid-point check in

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#26]
**Background**

**Acceptance criteria** 
- [x] mid point check in is on the calendar
- [x] Key attendees are available at scheduled time

**Tasks**
- [x] Email Christ list of potential roles to include
- [x] Get list of possible attendee names from Chris/Jay
- [x] Schedule event

**Definition of done**
- [x]  Meets acceptance criteria
