### ISSUE TITLE
Story board the to-be process of a new proposal becoming an executed agreement

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#267]
**Background**
This issue splits out the WF model updates from #219 and adds a storyboarding deliverable as an interim step. We want to focus on the experience folks will have at a high-level before we get down to the details of the actual interface.

**We'll know we're done when...**
- [x] We have storyboard of the to-be process that we can share with stakeholders.
- [x] The story board accurately conveys the to-be process laid out in the workflow model

**Tasks**
- [x] iterate on to be proposal creation flow, drawing on PA data mapping sheet in #176 
- [x] Account for signature in WF model and determine how whether an agreement has been signed is currently reflected in the DB
- [x] Create high-level story board that illustrates what the experience will be like for users
- [x] Review with Jay
- [x] Incorporate Jay's feedback
- [x] Share with stakeholders

**Comment by MelissaBraxton** [comment]
@jayrbergjr  - I split this task off of #219, since I think it's an important interim step. With that, what do you think about moving #219 back to the backlog? Because I don't think I'll be able to make much headway on it this sprint.

**Comment by jayrbergjr** [comment]
Sounds good.

**Comment by MelissaBraxton** [comment]
We got partway through our review w/ @jayrbergjr  on 6/7 - will finish review during co-working on 6/8.

**Comment by MelissaBraxton** [comment]
Incorporated feedback from @jayrbergjr  - Review mtg w/ broader group scheduled for Monday, 6/21.
