### ISSUE TITLE
Set status to "prop received" upon successful initial creation.

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/NRM-Grants-Agreements#268]
**Background**
When the initial required fields are in place, validated and we've satisfied the requirements outlined in our status change tracking spreadsheet (https://docs.google.com/spreadsheets/d/1wIktie0mGYUnC19ZdtcAeXrFV2ROYA_bR2VPyYVM7jI/edit#gid=1927696165) we should set the agreement status to PROP_RECEIVED.

**We'll know we're done when...**
- [ ] We've introduced a "submit for approval" button, separate from save, that triggers our full state validation (as opposed to save() which only runs required validations)
- [ ] We've validated all conditions are met in code
- [ ] We've set the status to PROP_RECEIVED and saved
- [ ] Tests are written as needed.

**Tasks**
- [ ] 
- [ ]

**Comment by tbaxter-18f** [comment]
If I'm reading the spreadsheet correctly we'll need to be pulling 

Fund status
Status date
FFIS doc ID

from somewhere (probably FMMI) before we can fulfill this.

**Comment by tbaxter-18f** [comment]
Possibly blocked by #269
