### ISSUE TITLE
Complete "cookbook" revisions/recommendations

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#27]
**Background**
Following up on our call w/ Sue, we want to revise the draft cookbook a bit more. 

**Acceptance criteria** 
- [x] Suggested revisions have been sent to Sue
- [x] Revisions incorporate design, engineering, product, and acq perspectives 

**Tasks**
- [x] Melissa reviews/edits
- [x] Miatta reviews/edits
- [x] Neil reviews/edits
- [x] Donny reviews/edits
- [x] Final pass to clean up comments
- [x] Email to Sue, Steve, and Sheri

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Thanks for taking this on, @tram. If you want to tag us either in Slack or the issue when you're ready for extra eyes, that'd be great!

**Comment by MelissaBraxton** [comment]
Draft including Sue's comments is[ here. ](https://docs.google.com/document/d/1ji96aNhkfwjAls_pzn6S_XMd8_HTyKK5g-58olXx1iw/edit?usp=sharing)
