### ISSUE TITLE
Set status to PROP_ACCEPTED

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/NRM-Grants-Agreements#270]
**Background**
Once the initial fields are in place, and an agreement has been submitted for approval. we need to capture whatn moves it to PROP_APPROVED. This may just be GMS review and sign-off. See https://docs.google.com/spreadsheets/d/1wIktie0mGYUnC19ZdtcAeXrFV2ROYA_bR2VPyYVM7jI/edit#gid=1927696165

**We'll know we're done when...**
- [ ]  We've introduced an "approval" as needed
- [ ]   We've validated all conditions are met in code
- [ ] We've set the status to PROP_ACCEPTED and saved
- [ ] Tests are written as needed.

**Tasks**
- [ ] 
- [ ]

**Comment by tbaxter-18f** [comment]
@MelissaBraxton can you verify we've captured the conditions that need to be met to go to PROP_APPROVED?
