### ISSUE TITLE
Create artifact library

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#271]
[Draft](https://docs.google.com/document/d/1hxeQfYv25ohCHboFprqk1C5rKiVys3GWnh_uxZEDB-k/edit#heading=h.yumf9nw86byr)

**Background**
As we prep for the next phase of work, let's create an index of our resources, artifacts, and everything in between. The goal of this is for us to have a one stop shop for finding resources that can be maintained over time as we develop more deliverables. 

Here's an example of an [artifact library](https://docs.google.com/document/d/1idBiOH7QkUGwNnFN4xmvBlmVwqXXAV_nRdR3M_tCC0Q/edit) I created for another project. 

**We'll know we're done when...**
- [X] We have a resource that we can keep continuously updated as new artifacts are developed. This can ultimately tie into the [where things stand](https://docs.google.com/document/d/1ZqjYrNmt7nW2OymOXeaYuzXgtf34OPWvhv4ka_qe1vM/edit#heading=h.iua7az3hzhp) vendor transition guide. 
- [X] We have outlined our key resources in a way that a new team member could use it for onboarding. 

**Tasks**
- [X] Take an initial inventory of relevant and helpful docs and artifacts.
- [x] Get team to review and add more resources.
   - [x] @MelissaBraxton 
   - [ ] @tbaxter-18f 
   - [ ] @neilmb 
   - [ ] @19mderose 
- [x] Create issues based on which artifacts should be published to the wiki.

**Comment by allisonnorman** [comment]
[Draft](https://docs.google.com/document/d/1hxeQfYv25ohCHboFprqk1C5rKiVys3GWnh_uxZEDB-k/edit#heading=h.yumf9nw86byr)
