### ISSUE TITLE
Schedule kick-off

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#272]
**Background**
We want to target a ~mid-July "kick-off" for the next phase of work and stakeholder alignment. We know schedules will be tough in the summar, and Jay said it will be helpful to get this on people's calendars soon so they know that this is coming up as questions around next steps are starting to bubble. 

**We'll know we're done when...**
- [x] We have scheduled the kick-off. 
- [ ] 

**Tasks**
- [x] Scope rough agenda and time (1 day, 2 days? how many hours?)
- [x] Identify attendees (tentatively: 18F team, Jay, Jamie, Melanie, Chris, Heather, Aaron)
- [x] Send meeting invite or save the date.

**Comment by allisonnorman** [comment]
@jayrbergjr is looking at 7/14 & 7/15, 2-4pm CT

**Comment by allisonnorman** [comment]
Jay sent placeholder invite!
