### ISSUE TITLE
Plan kick-off agenda

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#273]
**Background**
We want to start sketching out a plan for a kick-off type workshop. 

Here are some initial [ideas](https://docs.google.com/document/d/1ZqjYrNmt7nW2OymOXeaYuzXgtf34OPWvhv4ka_qe1vM/edit#heading=h.iua7az3hzhp). 

**We'll know we're done when...**
- [x] We have a high-level plan for an agenda
- [x] Associated issues to plan out activities or create decks (if necessary) have been created. 

**Tasks**
- [x] Co-work on other agenda items and potential activities
- [x] Mel has reviewed and added input
- [x] Neil has reviewed agenda and added input
- [x] Allison has reviewed and added input
- [x] @19mderose  has reviewed and added input
- [x] @jayrbergjr  has reviewed and added input
- [x] Sketch out who will take the lead on facilitating and developing the activity.

**Comment by MelissaBraxton** [comment]
I started a handy dandy[ workshop planning tool ](https://docs.google.com/spreadsheets/d/1ml2bwf-lDGe9vh92PI-EaGx7-ReGDAQUUGlWo6r78bs/edit#gid=0)for this (basically helps us easily game out different activities and how long things may take)

**Comment by MelissaBraxton** [comment]
Made new issue #316 to create deck.

**Comment by MelissaBraxton** [comment]
Looks like we still want @jayrbergjr and @19mderose to take a look at the draft [agenda ](https://docs.google.com/document/d/1ZqjYrNmt7nW2OymOXeaYuzXgtf34OPWvhv4ka_qe1vM/edit#heading=h.iua7az3hzhp)and [planning tool](https://docs.google.com/spreadsheets/d/1ml2bwf-lDGe9vh92PI-EaGx7-ReGDAQUUGlWo6r78bs/edit#gid=0) before we close this out.
