### ISSUE TITLE
Create onboarding doc and plan for new team members

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#275]
**Background**
As we plan on onboarding new team members to the project (and ultimately, a vendor), let's sketch out an onboarding guide and plan. 

**We'll know we're done when...**
- [x] We have an onboarding doc to share with new folks that navigates them through the onboarding process
- [x] Team has reviewed
- [x] We have a checklist that we can use to track newbie tasks in a Github issue. 

**Tasks**
- [x] Fill it in with everything someone would need to know to successfully onboard. [Link to onboarding doc](https://docs.google.com/document/d/1VkuVKqsFI9ojixaAPHaX-jrpUq0HP81Hgf53DUM-nRQ/edit#heading=h.my4hgyykpjmd).
- [x] Link README (#263), when ready
- [x] Create onboarding checklist GH issue (once reviewed by team)
- [x] Update relevant artifacts (Team practices page on wiki, Team charter) when possible so we can centralize that information and point to it rather than maintaining two sources of truth. 
   - [x] [Team practices wiki](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Team-practices)
   - [x] [Team charter](https://docs.google.com/document/d/1Mwx3pe9tYSNWga-gBVWmNcdbzS5pk_l7bWIK3oNyGXc/edit#) 
- [x] **Team review**
   - [ ] [Onboarding doc](https://docs.google.com/document/d/1VkuVKqsFI9ojixaAPHaX-jrpUq0HP81Hgf53DUM-nRQ/edit#heading=h.my4hgyykpjmd) - **READY FOR REVIEW + EDITS**
      - [ ] @neilmb 
      - [ ] @MelissaBraxton
      - [ ] @tbaxter-18f 
      - [ ] @allisonnorman - Final review (to close out issue)
   - [ ] [Team charter](https://docs.google.com/document/d/1Mwx3pe9tYSNWga-gBVWmNcdbzS5pk_l7bWIK3oNyGXc/edit#)  - **READY FOR REVIEW + EDITS**
      - [ ] @neilmb 
      - [ ] @MelissaBraxton
      - [ ] @tbaxter-18f 
      - [ ] @allisonnorman - Final review (to close out issue)
   - [ ] [Team practices wiki](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Team-practices) **READY FOR REVIEW + EDITS**
      - [ ] @neilmb 
      - [ ] @MelissaBraxton
      - [ ] @tbaxter-18f 
      - [ ] @allisonnorman - Final review (to close out issue)

**Comment by allisonnorman** [comment]
- [Link to README/onboarding doc](https://docs.google.com/document/d/1VkuVKqsFI9ojixaAPHaX-jrpUq0HP81Hgf53DUM-nRQ/edit#heading=h.my4hgyykpjmd)
- [Link to onboarding issue template](https://github.com/USDAForestService/NRM-Grants-Agreements/issues/new?assignees=&labels=&template=team-onboarding-checklist.md&title=) (for future new people)
