### ISSUE TITLE
Offboard Carter + eng download

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#278]
**Background**
Carter is leaving the project. He's learned lots about the problem space and the possible solutions. We should come up with a way to get some of that information out of his brain and recorded somewhere. When Carter leaves, we'll also have to make sure that his access is removed for the appropriate services, for FS and for our application.

**We'll know we're done when...**
- [ ] Carter's knowledge is recorded in a useable fashion for the team going forward
- [ ] Carter's access to systems is revoked appropriately

**Tasks**
- [ ] Draft a list of questions to get at what is in Carter's head
- [ ] Use our list of questions to do an interview and take notes
- [ ] Remove Carter's user from the prototype app
- [ ] FS offboarding: laptop return, eAuth access, etc.

**Comment by neilmb** [comment]
My notes in https://docs.google.com/document/d/1bszjpeSii0BQAya4h-grHh6MiW6h70J9DLurwqk_qFo

@beechnut ^^^^ those might be worth a read as you are coming up to speed on the application code/architecture
