### ISSUE TITLE
Provide training on working with technical vendors

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#279]
**Background**

When a vendor is slated to start, we should deliver training around working with vendors & core technical concepts:

-how to assess quality work, 
- acceptance, 
- core dev concepts around tech debt
- sussing out what’s necessary vs not.

**We'll know we're done when...**
- [ ] FS staff feel ready to accept and prioritize vendor's technical work

**Tasks**
- [ ] Develop training items
- [ ] Deliver a training session for FS product staff

**Comment by 19mderose** [comment]
Met with Greg Walker. He is in-between project and therefore available to facilitate. Topic-Provide training on working with technical vendors #314.

**Comment by cmajel** [comment]
@19mderose @neilmb flagging that I added #384 as a separate issue to provide more co-reviewing opportunities. I can see some overlap with this, though I see them as distinct. Let me know if that feels right to you, or if they should be folded into one issue.

**Comment by 19mderose** [comment]
> @19mderose @neilmb flagging that I added #384 as a separate issue to provide more co-reviewing opportunities. I can see some overlap with this, though I see them as distinct. Let me know if that feels right to you, or if they should be folded into one issue.

@cmajel This feels right. This is fine.

**Comment by 19mderose** [comment]
Spoke to Alex 8/16 needs to check with supervisor before committing to session. I will followup this week.

**Comment by 19mderose** [comment]
Confirmed with Ryan Hoffschneider for 9/17. Accepting technical work.
