### ISSUE TITLE
Write topline report

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#28]
**Background**
We want to summarize our early insights in a format that can be shared with partners and that helps us get a jump on our final report. 

**Acceptance criteria** 
- [x] Topline has been sent to partners
- [x] Topline includes insight from everyone on the team
- [x] It lives in a findable place in our drive

**Tasks**
- [x] Schedule topline jam session
- [x] Draft topline
- [x] Donny has added their insights
- [x] Miatta has added their insights
- [x] Neil has added their insights
- [x] Melissa has added their insights
- [x] Someone from the content team does an editing pass
- [x] topline sent to partners for review. 

**Definition of done**
- [x]  Meets acceptance criteria
