### ISSUE TITLE
How we work wiki page describes sprint ceremonies and prioritization

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#280]
**Background**

Our wiki page on how we work should describe the sprint ceremonies that our team participates in (Grooming, Retro, Demo, Planning) and the process or framework that the product owner will use in evaluating new issues.

**We'll know we're done when...**
- [ ] The wiki page https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Team-practices includes a description of our sprint ceremonies and prioritization framework

**Tasks**
- [x] Write a description of our sprint ceremonies and the goals of each one
- [ ] Develop and document a framework for how new issues will be prioritized.

**Comment by MelissaBraxton** [comment]
Will close this out after we've wrapped up #364
