### ISSUE TITLE
Set up automated accessibility testing in CI

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#282]
**Background**

As a first step to setting an accessibility testing baseline, we should set up Pa11y to run against our code on every commit using our CI setup. We have both the FS Jenkins setup and CircleCI. We should choose which one we want to use and leverage existing 18F and FS project setups.

**We'll know we're done when...**
- [ ] Pa11y is running in CI
- [ ] Either accessibility tests pass or we have logged tickets to correct the test failures

**Tasks**
- [ ] Research existing Pa11y setups at 18F and FS
- [ ] Configure it in either `.circleci/config.yaml` or https://code.fs.usda.gov/forest-service/CI-CD-Program

**Comment by neilmb** [comment]
OpenForest setup is described at https://github.com/USDAForestService/fs-open-forest/wiki/DevSecOps-Implemented
