### ISSUE TITLE
Deliver accessibility testing training

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#283]
**Background**

We should give a workshop for FS on the importance of accessibility and how to promote it technically, including how to use automated accessibility tools and how to perform manual accessibility testing

**We'll know we're done when...**
- [ ] We've delivered a workshop for the FS G&A team on testing accessibility

**Tasks**
- [ ] Figure out who should be invited
- [ ] Schedule the workshop
- [ ] Design the content
- [ ] Deliver the workshop
