### ISSUE TITLE
Deliver agile trainings

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#285]
**Background**

There's a variety of training that we want to provide for the FS G&A team during the transition process:

- Agile 101 training
- Integrating design research into agile sprints
- Usability testing quality heuristics
- Prioritizing a backlog and roadmapping
- Design research and 21st Century IDEA
- Open source and relevant resources

**We'll know we're done when...**
- [ ] Agile 101 training is done
- [ ] Integrating design research into agile sprints is done
- [ ] Usability testing quality heuristics is done
- [ ] Prioritizing a backlog and roadmapping is done
- [ ] Design research and 21st Century IDEA is done
- [ ] Open source and relevant resources

**Tasks**
- [x] Schedule weekly training hour at a time when USFS tech lead, product owner, and product manager can attend
- [ ] Identify who will deliver each training so that they can develop material

**Comment by 19mderose** [comment]
Workshop Kickoff meeting 7/1.

**Comment by MelissaBraxton** [comment]
This will need to get broken up into individual issues for each training topic.

**Comment by MelissaBraxton** [comment]
@19mderose It just occurred to me that we may also want to double check w/ Chris and Heather who else in NRM or G&A they want to be able to attend these and make sure they're on the invites

**Comment by jayrbergjr** [comment]
WO OG&A submitted a request to get on the AMC next agenda (23 Aug) to ask how/when they would like this training.

**Comment by 19mderose** [comment]
Update on #314
