### ISSUE TITLE
Set up unit testing for the existing prototype application

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#287]
**Background**

Django has a reasonable unit testing framework. We should set it up so that those tests are running in our CI, probably in CircleCI alongside our linting. 

**We'll know we're done when...**
- [ ] Tests are running and we can view the results on Github

**Tasks**
- [ ] Configure unit tests to run in CircleCI
- [ ] Write a few unit tests for the existing code to verify that the setup works
