### ISSUE TITLE
Set up integration testing for the existing prototype

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#288]
**Background**

Integration tests are somewhat more complicated to set up because the CI server has to actually run the server in one process and then execute tests against the server in a separate process and record the results. We should set up integration tests in CI, either in CircleCI or in the FS Jenkins instance.

**We'll know we're done when...**
- [ ] Integration tests are running in CI and we can see the results on each PR.
- [ ] We have at least a small number of tests to verify that the process is working.

**Tasks**
- [ ] Research integration test setups for Django/CircleCI
- [ ] Implement a few tests
- [ ] Verify that they are running
