### ISSUE TITLE
Create a staging environment with a connection back to the NRM dev database

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#293]
**Background**

An important part of our proposed technical solution is that our application can run against the Oracle database that is already in place at NRM. To de-risk that, we should create a "staging" environment in AWS that can run our application and make a connection back to NRM's "development" Oracle database.

**We'll know we're done when...**
- [ ] We have a staging endpoint for our prototype application that is displaying data from NRM's dev database

**Tasks**
- [ ] Start the process with FS Cloud Foundation group to set up the staging environment, including network connections back to Oracle in NRM's data center
- [ ] Figure out credentials for accessing the NRM database
- [ ] Figure out environment-specific deploy variables and pipelines

**Comment by tbaxter-18f** [comment]
Possible dupe of #309

**Comment by tbaxter-18f** [comment]
Supplanted by #309
