### ISSUE TITLE
Document communication processes with FS Cloud Foundation team

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#295]
**Background**

FS Cloud Foundation is a very new team and it isn't always clear how to get in touch with them, see what work they are scheduling, and what its status is. We should document on our wiki how we communicate with them and push them to get a FS Teams channel for their support requests.

**We'll know we're done when...**
- [ ] Request documents and standards from the Cloud Foundation team
- [ ] Participate in developing those standards with them
- [ ] We have a wiki page on who and how to talk with them
- [ ] There is a Teams channel for communicating with their team

**Tasks**
- [ ] 
- [ ]

**Comment by aaronburk** [comment]
I think having a wiki for how we communicate them is great idea.  As far as the TEAMS site for their group let be reach out and find out if they have something or if they are working toward some sort of communication approach for those already onboarded

**Comment by aaronburk** [comment]
@neilmb  I am thinking instead of pushing them toward a solution (TEAMS channel) I will likely just ask if they plan ot have a standard operating procedure of some sort in the near future where that the G&A project can reference through our Wiki as we move forward to ensure smooth communication and timely service?

**Comment by aaronburk** [comment]
![image](https://user-images.githubusercontent.com/25828899/121558908-10696080-c9e4-11eb-80b0-3f7af238140b.png)
