### ISSUE TITLE
Document how OG&A can evaluate design research expertise when they begin working with a new vendor team. 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#297]
**Background**
We want to make sure that there's design research expertise on the new vendor team that can guide the work after 18F is gone. 

**We'll know we're done when...**
- [ ] USFS has a clear understanding of what to expect from design research, how to identify red flags, and what they can do to mitigate any issues. 

**Tasks**
- [ ] Document design research expectations and skills needed for the project
- [ ] Review documentation with USFS Product Owner
- [ ] Add documentation to the wiki
- [ ] USFS leads a review of the documentation with relevant folks on the vendor team
