### ISSUE TITLE
Document process for integrating design research into agile sprints in the wiki

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#298]
**Background**
We want to make sure that we have an established process for integrating design research and usability testing into our sprints, that the process is well documented, and that the documentation is public and easy to find. 

**We'll know we're done when...**
- [ ] The wiki is up to date with design research process documentation  
- [ ] The documentation matches how we actually do it

**Tasks**
- [ ] Document process in wiki
- [ ] Demonstrate that we're following the process 
- [ ] Retrospectively re-review the confirm that the documentation is accurate and matches what we did / make any updates
