### ISSUE TITLE
Migrate Google docs content to FS Box drive and/or wiki

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#299]
**Background**
We'll want to wait on this until new 18F team mates have their credentials and can access Box. Using folders set up in #277. 

**We'll know we're done when...**
- [ ] All content in the USFS-18F shared folder in Google drive lives in Box

**Tasks**
- [ ] 18F staff have the right permissions to add and edit things in Box
- [ ] Copy files from Gdrive to Box
- [ ] Label Gdrive folders as deprecated?

**Comment by MelissaBraxton** [comment]
Blocked until 18F folks can access Box

**Comment by neilmb** [comment]
I think the same USDA onboarding process is also blocking #310 and #301.

**Comment by neilmb** [comment]
Matt is now in everything USDA.

**Comment by cmajel** [comment]
I verified today that I have access to Pinyon/Box! 🎉 

But, I'm not able to access links that have been shared before, like [this workshop recap](https://usfs.app.box.com/folder/137232493248). Is there an additional step of inviting us to a shared folder?

**Comment by cmajel** [comment]
With @aaronburk's help I now have access to [this box folder](https://usfs.app.box.com/folder/139644794024) and verified that I can [create folders and upload files](https://usfs.app.box.com/folder/144690701514).

The [workshop recap link](https://usfs.app.box.com/folder/137232493248) I shared before still does not work, but maybe it lives somewhere else? cc @MelissaBraxton who I believe created the recap in Box originally.
