### ISSUE TITLE
Create team charter

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#3]
**Background**
AS a team, we want to make sure we have conensus on how we want to work together. Melissa began a [draft team charter here](https://docs.google.com/document/d/1sRrMGzGxs3vK77WfS5mnkJmTr3aUns4E3HegiM3VlPI/edit#), but let's all dive in and edit until it really reflects the way we want to work. 

**Acceptance criteria** 
- [x] We have team charter that describes our desired working and communication practices
- [x] We have a team charter that clearly delineates each of our roles on the project

**Tasks**
- [x] Neil reviews draft team charter async
- [x] Donny reviews draft team charter async
- [x] Schedule charter co-working
- [x] Team co-working to refine the charter until everyone is happy with it 

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
@neilmb - I'm taking Donny and me off since we reviewed it together today. Once you're happy with it, feel free the issue / move to done.

**Comment by neilmb** [comment]
Entered my stuff in the doc and made some comments. Closing this for now.
