### ISSUE TITLE
Create useful package for IIT

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#30]
**Background**
We want to quantify some of the impacts of action/inaction to help our partners in their decision. making. Started [here](https://docs.google.com/document/d/1QvFKYycxzzoXGLPEPxvGuHz4GLenJpH-yoTPLUy5D-Y/edit)

**Acceptance criteria** 
- [ ] Justification includes accurate, quantitative data on metrics that our partners care about
- [ ] Draft has been sent to partners for review. 

**Tasks**
- [ ] Review examples
- [ ] Identify metrics and get data as needed
- [ ] write justification
- [ ] share with 18F team for review
- [ ] Refine and send to partners

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Example starts on page 19 [here. ](https://docs.google.com/document/d/1OiVdIgFOLPS3Qb29ODbaxs1j6Y_Tq5ItPKSGsy-WlRs/edit#)

**Comment by neilmb** [comment]
We may need to do some research/interviews on the FS governance process to be able to make useful recommendations.

**Comment by allisonnorman** [comment]
@neilmb @MelissaBraxton - Cleaning up the board. Seems like we could close this as invalid/no longer needed. Can you confirm?

**Comment by neilmb** [comment]
Yes, we have the related work in other tickets.
