### ISSUE TITLE
Onboarding checklist - Magdaline

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#301]
**Current team to-dos**
- [x] Confirm [README](https://docs.google.com/document/d/1VkuVKqsFI9ojixaAPHaX-jrpUq0HP81Hgf53DUM-nRQ/edit#heading=h.my4hgyykpjmd) is up-to-date, and add new team member to team list.
- [x] Send invite to Slack channels (#fs-nrm-ga and #usfs-ga-partners).
- [x] Send invite to [Github repo](https://github.com/USDAForestService/NRM-Grants-Agreements/settings/access).
- [X] Share access to project Google Drive.
- [x] Send invite to [G&A Mural room](https://app.mural.co/t/gsa6/r/1612999180491).
- [x] Send invite to [google group](https://groups.google.com/a/gsa.gov/g/18f-usfs-nrm)/distro list (18f-usfs-nrm@gsa.gov).
- [x] Send invites to weekly meetings.
- [x] Schedule intro meeting with Jay.
- [x] Kick off FS onboarding process. - @rrefoy
- [x] Create a Django admin username and password.
- [ ] Schedule a team kickoff. (@neilmb - you wanna drive this one?)
   - [ ] Review [team charter](https://docs.google.com/document/d/1Mwx3pe9tYSNWga-gBVWmNcdbzS5pk_l7bWIK3oNyGXc/edit#heading=h.np0y2bjky8h) as a group.
   - [ ] Give a tour of codebase/design assets/strategy docs/Mural.
   - [x] Audit meetings - New team members joining gives us a great opportunity to revisit our recurring team meetings and adjust schedules if necessary (to adjust for time zones, etc) - see [example meeting exercise doc](https://docs.google.com/document/d/1MIC1ifST_SfZRxFDU_23Igf_7mYniq1JUBTpZIya9oA/edit?usp=sharing)

**Newbie onboarding checklist**
- [x] Review our project [README](https://docs.google.com/document/d/1VkuVKqsFI9ojixaAPHaX-jrpUq0HP81Hgf53DUM-nRQ/edit#heading=h.my4hgyykpjmd).
- [x] Review our [Team Charter](http://gBVWmNcdbzS5pk_l7bWIK3oNyGXc) to see how we work, how we communicate, and our weekly rituals.
- [x] Schedule coffees with the team to talk through their work and to get to know each other (both 18F and partner).
- [x] Get a demo of the current product.
- [x] Get an account for any new-to-you tools (we use Github, Mural, and Zenhub).
- [x] Once you get a username and password, log in to the Django application and explore.
- [ ] Review [artifact library](https://docs.google.com/document/d/1hxeQfYv25ohCHboFprqk1C5rKiVys3GWnh_uxZEDB-k/edit#heading=h.yumf9nw86byr) (Note: we are still adding to this!) 
- [ ] Read recent [project reflection](https://docs.google.com/document/d/1xFj26iqM85XrcFIda94lb2izLTHTsTWKRDNClJ16q7c/edit?usp=sharing)
- [x] Install Microsoft teams on GSA laptop and test that you can join before you have a FS laptop/account (a teammate should be able to help with this).
- [ ] Complete USFS tech setup.
   - [x] Fill out USDA onboarding paperwork, when prompted. This will start the process to get FS equipment and a Lincpass (USDA’s version of a PIV card). This could take a couple months, so please fill out the paperwork as quickly as possible.
   - [ ] Obtain USDA Lincpass.
   - [x] Obtain FS laptop.
      - [x] Confirm access to MS Teams and USDA email, once accounts are set up.
      - [x] Complete any mandatory trainings in AgLearn. 
      - [ ] Confirm access to G&A Box account (Jay can invite you).

**Comment by 19mderose** [comment]
FS IT-Help Desk activated my domain and help set up teams.
