### ISSUE TITLE
Sketch out training/change management training series

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#302]
**Background**
As part of transition planning, we want to sketch out a high-level training series for the FS team. This feels like a good pairing task for Allison and @19mderose as she ramps up.

I'm thinking this looks like a series of topics, goals, and a list of potential guest speakers, when applicable. 

**We'll know we're done when...**
- [x] We have drafted a training plan (based on transition tasks, overall project timeline)

**Tasks**
- [x] Draft plan
- [ ] Get input from team
   - [ ] @neilmb 
   - [x] @MelissaBraxton 
   - [ ] @19mderose 
- [X] Add link in artifact library under transition section

**Comment by allisonnorman** [comment]
I started sketching this out in [Mural](https://app.mural.co/t/gsa6/m/gsa6/1623707762342/de870a9c18474b1bf6f81cf75966460fb3f8fa03). I pulled from the change management issues and prioritized based on the prioritization exercise.

**Comment by aaronburk** [comment]
this looks great.  Lot of challenges in USFS for training/willing ness to implement in all these areas.  Just a quick note nearly everything mentioned aligns with the USDA Open Government efforts and FITARA and the Federal Digital Strategy
https://www.usda.gov/sites/default/files/documents/usda-open-gov-plan-v4.0.pdf
https://www.usda.gov/open

**Comment by allisonnorman** [comment]
Also started putting together a [tentative schedule](https://docs.google.com/spreadsheets/d/12otMb9wv3DeAbRMLW8RaF_Dn6GqmlZAUGQEFBQCnHP4/edit#gid=0). Still to add: more potential training decks and guest speakers.

**Comment by allisonnorman** [comment]
I added some more thoughts on the [schedule draft](https://docs.google.com/spreadsheets/d/12otMb9wv3DeAbRMLW8RaF_Dn6GqmlZAUGQEFBQCnHP4/edit#gid=0) around potential topics and concepts to cover. These are just ideas and over time, we will have a better sense of where the project is and can reschedule based on current, relevant topics.

@neilmb As part of the meeting defrag, do you want to take on figuring out which meeting will be used for these deep dives? If we're not ready to do that quite yet, I can also put this issue in the waiting column. 

Would also love some eyes from @MelissaBraxton and @19mderose to see if this feels helpful for now and if you feel like this is something the team can roll with as part of the change management planning or if there is anything else I can do to help in the meantime before closing this issue out.

**Comment by allisonnorman** [comment]
I created #314 to schedule this out.
