### ISSUE TITLE
Prioritize change mgmt/transition success scenarios

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#303]
**Background**
We've developed change mgmt and transition (from 18F > vendor team) success scenarios [here](https://docs.google.com/document/d/1YOlrpQXbbWwYcE-LYeqoavvMDolHjIgBmfQorp8Ft3c/edit#). We need to work with USFS folks to prioritize these scenarios and our work in the near term and when a vendor arrives. 

**We'll know we're done when...**
- [x] We have a shared understanding of the priority level of change mgmt/transition success scenarios
- [x] Transition plan doc. accurately communicates these priorities

**Tasks**
- [x] Create Mural template for prioritization mtg
- [x] Schedule one hour mtg to include @jayrbergjr and @aaronburk 
- [x] Conduct activity
- [x] Revise transition plan doc to reflect priorities

**Comment by MelissaBraxton** [comment]
We could use something like [this Mural.](https://app.mural.co/invitation/mural/gsa6/1623280772028?sender=melissabraxton2796&key=d3fd94cb-9c4b-460d-9c71-7a1c27606aa5)

**Comment by MelissaBraxton** [comment]
Un assigning myself and passing this to you @neilmb, since you'll be facilitating.
