### ISSUE TITLE
Set up staging and production environments on FS AWS

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#309]
**Background**

We currently have a development environment on FS AWS. We should begin ASAP getting the staging and production environments created on that platform. The staging AWS environment needs to be configured to connect back to the NRM development Oracle database. The production AWS environment needs to be configured to connect back to the NRM production Oracle database.

**We'll know we're done when...**
- [ ] Our prototype application can be deployed in staging with access to NRM's legacy development database.
- [ ] Our prototype application can be deployed in production with access to NRM's legacy production database.

**Tasks**
- [ ] Describe to the FS Cloud Foundation team what we want and get them started working on it
- [ ] Watch that team closely to make sure that they are making steady progress at creating the environments.
- [ ] Figure out credentials for accessing the NRM database
- [ ] Figure out environment-specific deploy variables and pipelines

**Comment by tbaxter-18f** [comment]
In my opinion, we could defer this until we get closer to needing a production environment. I would suggest scheduling so these are in place 4-6 weeks before a production environment is needed, whenever that is.

**Comment by neilmb** [comment]
This replaces #293 since creating staging and production can probably be done at the same time.

**Comment by aaronburk** [comment]
just noting that as this work is done there a USDA Cybersecurity requirement that no live data is allowed  outside of production environment.  As of now there is a team working o  this task in NRM (mostly in DEV right now.  That said this requirement may need ot be kept in mind in NRM is planning to introduce data in the cloud environments moving forward

**Comment by neilmb** [comment]
Started the conversation with the FS Cloud Foundation team in MS Teams.

**Comment by neilmb** [comment]
Asked again on Teams about how to get this done.

**Comment by neilmb** [comment]
Meeting coming up on Thursday July 15th to learn more about requirements for this.

**Comment by neilmb** [comment]
This is on hold now until we do #349

**Comment by neilmb** [comment]
Meeting with Mark Awad and Thompson Grant scheduled for August 25.
