### ISSUE TITLE
Schedule G&A learning series

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#314]
**Background**
We drafted a [schedule](https://docs.google.com/spreadsheets/d/12otMb9wv3DeAbRMLW8RaF_Dn6GqmlZAUGQEFBQCnHP4/edit#gid=0) in #302. Let's continue this effort and create an invite with attendees at least for the initial sessions.

**We'll know we're done when...** 
- [x] We have scheduled the learning series (all, or some of them)
- [ ] We have created issues for upcoming sessions

**Tasks**
- [x] Identify the format (reoccurring meeting with optional attendees based on content, ad hoc meetings, etc)
- [x] Identify the participants
- [ ] Create issues to track developing content for the sessions.
- [x] Meet with Alan B to discuss agile trainings. 
- [ ] Discussion with Callie and Steve (mary.mcconnell@usda.gov) audience's availability.

**Comment by 19mderose** [comment]
Workshop Kickoff meeting 7/1.

**Comment by 19mderose** [comment]
Met with Alan B regarding Agile Training. He is available any time after 8/10/2021. Deliver agile trainings #285.

**Comment by 19mderose** [comment]
Met with Greg Walker. He is in-between project and therefore available to faciliate. Topic- Provide training on working with technical vendors #279.

**Comment by MelissaBraxton** [comment]
@19mderose - Do we have an issue in this sprint to cover the topic coming up on 8/6 (I couldn't find one)? We'd talked about @neilmb focusing on architecture, but I don't know if it's on his radar.

**Comment by 19mderose** [comment]
I will check with Neil.

**Comment by 19mderose** [comment]
Pause for now. However, Heather thinks these trainings are valuable. Partner is searching for AMC Leadership availability in order to service a wider audience.
Time frame Oct-Dec 2021
