### ISSUE TITLE
Create workshop content

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#316]
**Background**

**We'll know we're done when...**
- [x] Workshop deck covers topics listed [here](https://docs.google.com/spreadsheets/d/1ml2bwf-lDGe9vh92PI-EaGx7-ReGDAQUUGlWo6r78bs/edit#gid=0)
- [x] Material can be delivered in 2, 2.5 hour sessions
- [x] People responsible for facilitating different sections have reviewed and approved the material they'll present

**Tasks**
Create material that covers: 
- [x] Team intros and icebreaker
- [x] Intro from 18F (who is 18F, how we work, etc.)
- [x] Roadmap alignment material and activity
- [x] Risks discussion
- [x] Mini retro (day 1)
- [x] Role clarification
- [x] "how we collaborate" 
- [x] User research refresher + empathy building (what we know and how we know it)
- [x] Story board and (service blueprint ?)
- [x] Change management and transition planning
- [x] Mini retro (day 2)
