### ISSUE TITLE
Analyze interview data

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#32]
**Background**

**Acceptance criteria** 
- [x] Data is tagged with major themes
- [x] Analysis artifacts are in shared file

**Tasks**
- [x] Review interview notes and pull quotes
- [x] Tag quotes with main themes
- [x] Summarize insights in topline
- [x] Save file in shared drive

**Definition of done**
- [x]  Meets acceptance critera

**Comment by MelissaBraxton** [comment]
Sheet is[ here](https://docs.google.com/spreadsheets/d/1I0oGrUVuXhV1xwW8JZqqybaiNDVqrDltpF22-K4auYQ/edit#gid=0).  Moving to waiting since we have a few more interviews to do.
