### ISSUE TITLE
Sketch out release engineering processes

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#321]
**Background**

We need an understanding of what testing, development, staging, and production environments we will need and how changes will flow through those environments and get code-reviewed, approved by the product owner, and deployed in the production environment.

**We'll know we're done when...**
- [ ] We have a document describing how changes make their way to production
- [ ] We have started the process about getting those corresponding environments set up in FS AWS

**Tasks**
- [ ] Write a proposed process document on the Wiki
- [ ] Get feedback either synchronously or asynchronously and finish a revision

**Comment by neilmb** [comment]
This should include conversations with ISSO (Hieu Nguyen) about what approval process is going to be required for releasing into the real production environment.

**Comment by beechnut** [comment]
Noting here: we're momentarily using Claudia.js for Lambda deployment, for local & sandbox work. I expect that Claudia will be used only temporarily, to be superseded by Terraform, Ansible, or something equivalent once we stand that up as part of this work.

**Comment by beechnut** [comment]
Here's the [Wiki page on the Release Engineering Process](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Release-Engineering-Process). I've added the QASP chart and the code quality metric, and added implementation details/status.

Very much a first draft, so please edit/comment, and there's a bit of work to do to get the pipeline fully implemented.

**Comment by beechnut** [comment]
[First draft of dev -> staging -> prod is in Mural here](https://app.mural.co/t/gsa6/m/gsa6/1629906349964/c1622d2c54103bf1472dbb660e0099af71ef55a1?sender=u4f47cdf98671301519091262). Lots to discuss, figure out, and edit.

**Comment by beechnut** [comment]
Moved to **Waiting**: waiting for project pivot work to finish before picking this up.
