### ISSUE TITLE
As a proposal creator, I need to be able to submit a new proposal without including the BOC so that I don't have to wait for BAs or GMS to give me the additional info before I can route my proposal for review. 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#322]
**Notes**
In the new proposed workflow, budget analysts, NOT program managers, will submit funds reservations requests (formerly "commitments"). The current mocks for program managers' proposal submission are designed to include a funds reservation request as part of the proposal submission process. We need to redesign what is currently the "commitments" part of proposal approval to reflect this change.

**We'll know we're done when...**
- [ ] Program Managers can submit funding info that BAs require in order to request funds reservation from FMMI
- [ ] Program Managers can certify that they approve BAs to request funds from their job code
- [ ] Program Managers can submit proposals without including budget object code

**Supporting documentation**
- [ ] [Proposal creation, approval, and execution WF](https://app.mural.co/t/gsa6/m/gsa6/1624379057943/2a98b1294a17025d86e3e7d95a2e509ab4f1740f)
- [ ] Related to #248

**Tasks**
- [ ] Revise mocks to enable new workflow
- [ ] Document considerations for BA funds reservation request interface in a new issue. 
- [ ] PO approves mocks
- [ ] Dev implements changes
- [ ] Usability tested

**Comment by cmajel** [comment]
Noting that this is related to #325
