### ISSUE TITLE
As a proposal creator, I need to understand what "cooperator DUNS#" means and where I can go for more info so that I can confidently enter the correct data. 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#323]
**Notes**
This story covers a need that came out of sprint pine cone cap research on the proposal submission form. Where proposal submitters are inputting partnership details, we need to add explanatory text or in context glossary link to help folks understand DUNS#. 

**We'll know we're done when...**
- [ ] Users have a clear path from the proposal creation form to an explanation of what DUNS# is and where to get it

**Supporting documentation**
- [ ] sprint pine cone cap research report
- [ ] Related to #248

**Open questions**
- [ ] Is there a glossary link on NRM intranet we can link to? 
- [ ] If it's behind NRM authentication, how will that work? 

**Tasks**
- [ ] Revise mocks to reflect change
- [ ] PO approves mocks
- [ ] Design/dev feasibility review 
- [ ] Devs implement change

**Comment by cmajel** [comment]
[Noting this GSA article](https://www.gsa.gov/about-us/organization/federal-acquisition-service/office-of-systems-management/integrated-award-environment-iae/iae-systems-information-kit/unique-entity-identifier-update) about SAM.gov's transition from DUNS to UEI for entity identification.
