### ISSUE TITLE
Tweaks to the "commitments" part of the proposal creation form to reflect new workflow

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#325]
**Notes**
We need to significantly revise the "commitments" part of our new proposal flow to reflect the [current to-be workflow](https://app.mural.co/t/gsa6/m/gsa6/1624379057943/2a98b1294a17025d86e3e7d95a2e509ab4f1740f) model for proposal creation, approval, execution.

**We'll know we're done when...**
- [x] all language re: "commitments" matches FMMI language "funds reservation requests"
- [x]  The job code field(s) is a combo box that helps people quickly find the correct job code.
- [x] program can certify that it's ok for budget to request the amount
- [x] proposal submitters are not asked for BOC
- [x] program submitters see an understandable explanation of what happens after they click "submit" 

**Supporting documentation**
- [ ] [current to-be workflow](https://app.mural.co/t/gsa6/m/gsa6/1624379057943/2a98b1294a17025d86e3e7d95a2e509ab4f1740f) 

**Open questions**
- [ ] 

**Tasks**
- [x] Mock up changes
- [x] PO approves
~- [ ] Usability tested~

**Comment by cmajel** [comment]
@MelissaBraxton clarifying the scope of this:

* This is to adjust our mocks of what program managers interact with when creating an agreement so that they can provide enough information to...
  * say where money is coming from and how much
  * give enough info to a budget approver that they can assign a BOC and commit the funds
 * This issue is NOT getting into what budget specialists would see when they see commitment requests

**Comment by MelissaBraxton** [comment]
Removed from acceptance criteria as they're only relevant to BAs w/ the new WF where PMs are no longer submitting funds reservations requests 
- [ ]  People can link to multiple workplans to funds reservation requests. 
- [ ]  People can add more than one job code to funds reservation requests.

**Comment by cmajel** [comment]
I've put together a few options for review. 
* Here's a link to [the Figma file](https://www.figma.com/file/AOWq8IWGSAUGZiqZ1nZSeF/USFS-Grants-and-Agreements-Playground?node-id=1017%3A5678)
* Here's what our [commitments flow](https://gsa.invisionapp.com/console/share/9610WO0NRF7V/619008511) looked like during our last usability test
* Screenshot previews below.

I explored two options:
* Option 1: Retain the basic structure of our existing commitments flow, but update the language and fields
* Option 2: Explore what importing data from Workplan directly may look like.

I've noted questions in the mocks, but summarizing some comments and questions here:
* Should fiscal year be an editable field, or just displayed after submission?
* Do friendly names for code data sets (org code, job code) exist to make it easier to search?
  * Does budget org code link up to org code? Could this be prepoped?
* Does a Workplan record = a single funding reservation request? Multiple?
  * Could we get all the data we need from Workplan to populate a funding reservation request, or would a PM need to add more? 
* I tried a simplified confirmation page with just approvals and a routing notification.
  * Do we need to preview the whole agreement for their review? Experimented with removing this. 


## Option A: Similar flow
![hp-pc--funding-01 01--funding-landing](https://user-images.githubusercontent.com/2374206/126811054-ea27b3e5-c120-4092-a514-22fadc1f2c02.jpg)
![hp-pc--funding-01 02--search-wp](https://user-images.githubusercontent.com/2374206/126811056-f9d86ba3-ce38-404e-96f7-9fa406d6d68d.jpg)
![hp-pc--funding-01 03--landing-w-wp](https://user-images.githubusercontent.com/2374206/126811057-33c43f83-5773-4555-9318-c075b1ea45e3.jpg)
![hp-pc--funding-01 04--enter-request](https://user-images.githubusercontent.com/2374206/126811059-81657f43-da85-46a6-a3db-6da204d60479.jpg)
![hp-pc--funding-01 05--submit](https://user-images.githubusercontent.com/2374206/126811062-37e618b3-92b9-4686-b8a9-d0c1a6d5bd77.jpg)


## Option B: Workplan import option
![hp-pc--funding-02 01--funding-landing](https://user-images.githubusercontent.com/2374206/126811114-73941c0d-c5e7-4398-830c-216b35a81b4a.jpg)
![hp-pc--funding-02 02 1--search-wp](https://user-images.githubusercontent.com/2374206/126811115-1f109205-028a-4648-812e-95db22add191.jpg)
![hp-pc--funding-02 02 2--import-wp](https://user-images.githubusercontent.com/2374206/126811116-eb10809b-a652-496f-82da-df3b09174ed7.jpg)
![hp-pc--funding-02 03--submit-wp-import](https://user-images.githubusercontent.com/2374206/126811118-697bd855-8e55-4b89-92aa-ec38f1a2939c.jpg)

## Updated submit page language
![hp-pc--funding--submit](https://user-images.githubusercontent.com/2374206/126811222-e95c4b14-d5f5-40a4-8dba-daf1d7470b91.jpg)

**Comment by MelissaBraxton** [comment]
I think the first approach (not assuming workplan link) is the lightest weight way to try and meet these needs, but will defer to @jayrbergjr.

Some thoughts on a few of your Qs (the rest we can discuss w/ Jay!) 

Should fiscal year be an editable field, or just displayed after submission?
 - I have in my notes that it's currently auto-popped w/ current FY. My hunch is that users would like to see that (rather than have it hidden until the end), but we can log that as a secondary research Q. 

Does a Workplan record = a single funding reservation request? Multiple?
 - Additional things to clarify - w/ PMs no longer submitting the funding reservation request, how might they want to chunk up how they tell BAs about the funding they'd like to use? What language makes sense? Is it "do you plan to use funds from multiple workplans? Budget org code? job codes

**Comment by MelissaBraxton** [comment]
Now that we are planning to validate WF changes primarily using the WF model and the story board, I'm wondering if we want to pause more work on this pending what we learn from that research? 

What do you think, @jayrbergjr and @cmajel?

**Comment by cmajel** [comment]
I've updated this a bit for coworking tomorrow based on an initial review with @MelissaBraxton 

[Figma link](https://www.figma.com/file/AOWq8IWGSAUGZiqZ1nZSeF/USFS-Grants-and-Agreements-Playground?node-id=1017%3A5678)

Changes include
* Removed "funding reservation" language
* Exploring `add jobcode` as the action
* Removed workplan, as we anticipate this will come earlier
* Removed fiscal year and budget fiscal year from funding form
* Adjusted column ordering
* explored splitting up the approve and submit page language, aligned with #322 language, and explored what it would look like if a PM wasn't creating the proposal

A thought: Since the last step of the form, `approve and submit`, deals with roles, I experimented with moving `agreement team` from the 3rd step to the 4th step so that it directly precedes `approve and submit`. My thought is that having these closer together helps people stay in the same frame of mind of "who sees this next."

Some questions:
* Is this language around funding correct? 
* Do we know if budget org code can be inferred from org code?
* I'm also assuming budget fiscal year could be inferred from job code...is that a correct assumption?
* Is there text helpers in WP (or elsewhere) that could make budget org code and job code more easy to navigate?

**Comment by cmajel** [comment]
We reviewed this with @jayrbergjr yesterday. I've added #377 as a follow on task to learn more about job code data sources and structure.

@MelissaBraxton wondering if we need a follow on task for usability testing of proposal creation flow that would include some of this work...

**Comment by MelissaBraxton** [comment]
@cmajel  - Curious what @jayrbergjr thinks, but I'm feeling like we may pivot to prioritizing getting a start on more of the core functionality before we refine these mocks further. I'd see usability testing of these concepts come into play at the time we or the new vendor picks up #322. I added it as a task on 322 for now.

**Comment by MelissaBraxton** [comment]
@jayrbergjr w/ the change to covering usability testing down the road, can we close this out?

**Comment by jayrbergjr** [comment]
@MelissaBraxton We can close this one out.
