### ISSUE TITLE
Refine agreement creation WF model - unhappy path and data flow

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#326]
**Background**
We drafted the happy path to be workflow for new, outgoing fund agreements being approved, but we haven't yet designed how we'll handle rejections, and errors, etc. 

**We'll know we're done when...**
- [x] The to-be wf model shows how **most common** rejections and errors are handled. 
- [x] We've documented any edge cases that may need to be handled down the road
- [x] People know what info is entered as a part of each task in the WF

**Tasks**
- [x] Map out rejections and error handling in the WF model
- [x] Map out info flow / tie info input to WF tasks
- [x] Walkthrough with @jayrbergjr and SMEs
- [x] Revise based on feedback
~- [ ] Post to GitHub~

**Comment by MelissaBraxton** [comment]
This is going to be out of scope for me this week (7/19-7/23).

**Comment by MelissaBraxton** [comment]
@cmajel  - If you find yourself with bandwidth tomorrow, I've started the detailed info modeling [here.](https://docs.google.com/spreadsheets/d/1wIktie0mGYUnC19ZdtcAeXrFV2ROYA_bR2VPyYVM7jI/edit#gid=892182007) in the first tab. May not be 100% self explanatory, so we could just as well pick it up next week in a co-working session.

**Comment by MelissaBraxton** [comment]
Removed post to GH task, since that is now covered in #379.
