### ISSUE TITLE
Create user descriptions or personas

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#33]
**Background**

**Acceptance criteria** 
- [x] Personas include concise descriptions of users goals, behaviors, pain points, and representative quotes

**Tasks**
- [x] Review data 
- [x] Create persona drafts
- [x] Review as a team
- [x] Revise/finalize based on team feedback

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Drafting [here](https://docs.google.com/document/d/1fVpmxPm8G6XoRGfP28lfCeIrwHyxct9PoZ6l2-6ABmA/edit)
