### ISSUE TITLE
Draft vendor interview Qs

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#333]
**Background**
This is covers how we'll support NRM in reviewing applicants on their modernization contract. 

**We'll know we're done when...**
- [x] We have curated resources on how NRM might evaluate applicants on the design, research, and engineering expertise needed for this project.\

**Tasks**
- [x] Review past examples
- [x] Write new Qs in light of specific project needs
- [x] Review with Heather et al.

**Comment by MelissaBraxton** [comment]
Have an initial list, but need clarification on demo procedures before we can finalize. Pinged the COR for clarification on 7/23. Can revisit this when we hear back from them.
