### ISSUE TITLE
Add infrastructure diagram to roadmap Wiki page

### ISSUE THREAD

**Issue by beechnut** [18F/NRM-Grants-Agreements#336]
Aaron mentioned that folks have questions about when different parts of the NRM infrastructure are planned to go offline/be migrated. He said that it would be helpful to include an infrastructure diagram for each module in the roadmap, to clearly communicate this.

**We'll know we're done when...**
- [x] We have diagrams added to the wiki.
- [x] Aaron signs off.

**Tasks**
- [x] Add diagrams to the wiki.

**Comment by aaronburk** [comment]
Thanks for creating this Matt ( I have forwarded it to Adam Shepherd as well)  not sure if he onboarded and getting these notifications yet

**Comment by neilmb** [comment]
First draft diagrams at 

https://docs.google.com/drawings/d/1ZE0Vo2HcuC_9p9avfGu2f5XZ_o7IjWZuyNlKBatR3vU
https://docs.google.com/drawings/d/1I65tII_WK1OivazQA4l9zdbdQ5UpruI27WJKImBVvV0
https://docs.google.com/drawings/d/1B8_gDRueLcOcth3T_eWPhzQdrKcbxoljB9d1GojM7rU

**Comment by neilmb** [comment]
@aaronburk @AdamUSDA I changed the diagrams based on our conversation this morning. 

Can you review https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Product-roadmap and comment here if it looks good to you?

**Comment by aaronburk** [comment]
These look good to me.  Thanks so much!

**Comment by AdamUSDA** [comment]
This looks good from a high level perspective.
