### ISSUE TITLE
Write cooperator interview protocol

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#34]
**Background**

**Acceptance criteria** 
- [x] Protocol is complete and available in shared drive

**Tasks**
- [x] Write research Qs and interview protocol

**Definition of done**
- [x]  meets acceptance criteria
