### ISSUE TITLE
Write up workshop summary

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#345]
**Background**

**We'll know we're done when...**
- [x] We have documented the outputs of our re-KO workshops
- [x] Document is easily accessible

**Tasks**
- [x] Write up summary
- [x] Have a team member review
- [x] Include w/ weekly ship
- [x] post to Box and/or the wiki?

**Comment by MelissaBraxton** [comment]
Draft summary is [here](https://docs.google.com/presentation/d/1fgXlRN_8z1Oz4z1PXy6n-yUSxBw1vjyRrythccMXh8k/edit#slide=id.ge5d92941d4_0_135)

Passing to @19mderose, @neilmb, or @cmajel for peer review?

**Comment by cmajel** [comment]
I can take a look this afternoon.

**Comment by neilmb** [comment]
Reviewed and left a comment. ✔️

**Comment by cmajel** [comment]
Reviewed and left a few suggestions; looking good 👍🏻

**Comment by MelissaBraxton** [comment]
Posted to Box [here](https://usfs.app.box.com/folder/137232493248).
