### ISSUE TITLE
Conduct core team KO / align on collaboration practices

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#346]
**Background**
We ran out of time at the workshops to go over "how we work" content. We'll want to quickly get together with USFS PM, PO, and Tech Lead to do that, as we'll begin working together in this new way on July 26 when the PM and PO are back from vacations. 

**We'll know we're done when...**
- [x] 18F and USFS folks have reviewed and have consensus on "how we work" content
- [x] Wiki "how we work" page matches agreed upon practices
~- [ ] We have a team charter?~

**Tasks**
- [x] Schedule meeting w/ 18F team, tech lead, PM, and PO
- [x] Finalize content
~- [ ] Develop team charter as a team~
- [x] Meet

Document agreed on practices in wiki:
- [x] Roles
- [x] Current tooling (for now) 
- [X] Description of sprint ceremonies
- [X] code of conduct
- [x] ADR practices
- [x] How technical work is accepted
- [x]  How design work is accepted

**Comment by MelissaBraxton** [comment]
I can update the wiki tomorrow. 

If we want a team charter, then we may want to have it as a separate issue.

**Comment by MelissaBraxton** [comment]
Team charter tasks and acceptance criteria are now in #365

**Comment by MelissaBraxton** [comment]
@beechnut - I added a few tasks to call out specific sections of the wiki that need updating. Would you be able to help out with updating [platform and technologies](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Platform-and-Technologies) and adding something about ADRs to our [team practices](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Team-practices)?

@neilmb would you be up for filling in the technical work section[ here](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/How-work-is-accepted)?

**Comment by neilmb** [comment]
@MelissaBraxton I adapted the content from the slide deck into the Wiki as a first pass for that page.

**Comment by MelissaBraxton** [comment]
Thanks @neilmb  - made a few minor tweaks, but otherwise LGTM.

**Comment by neilmb** [comment]
@MelissaBraxton Could you take a look at the "How we work" content on the wiki and verify that this ticket is done?
