### ISSUE TITLE
Research and document CI/CD setup

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#347]
**Background**

CI/CD tooling is an important piece of the technical roadmap. We should research the tools and setup that are available for this at the FS from the Cloud Foundation team and then document what we find out.

**We'll know we're done when...**
- [ ] @AdamUSDA signs off on what we find out

**Tasks**
- [x] Research the CI/CD setup that is in place with Cloud Foundation for our prototype app
- [ ] Document that setup on the Github wiki

**Comment by AdamUSDA** [comment]
Hey @neilmb we should coordinate with Jaiprakash, Patchamuthu (jay) who is also looking at CI/CD tools. There are some that are being used in Legacy apps but there maybe other options that are a better fit for our Modernization teams.
