### ISSUE TITLE
Transition to FS CI/CD setup

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#348]
**Background**

In #347, we documented what CI/CD tooling we would use. Once that research is done, we should convert our existing code to use that setup.

**We'll know we're done when...**
- [ ] Our repo is running all of its testing and deployment on the FS CI/CD setup, as specified by [Release Engineering Process](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Release-Engineering-Process) and [CI/CD Pipeline](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/CI-CD-Pipeline) pages

**Tasks**
- [ ] Make PRs to do as much reconfiguration as possible alone
- [ ] Swap out Django-based migration for TypeScript
- [ ] Convert linting to the new setup
- [ ] Convert unit tests to the new setup
- [ ] Convert Pa11y to the new setup

**Comment by beechnut** [comment]
Emailed Matt Reiss to kick off the work.

**Comment by beechnut** [comment]
[Documented CI/CD process on the Wiki here.](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/CI-CD-Pipeline)

**Comment by AdamUSDA** [comment]
Hey @beechnut @neilmb ,

The Documented CI/CD process looks good. Can we include diagram of what that process will look like. 

Can we also have a list of the items in that process that we are asking Ops to setup for us. 

Thanks

**Comment by beechnut** [comment]
@AdamUSDA Here's a start on a flowchart: [G&A CI/CD Flowchart](https://app.mural.co/invitation/mural/gsa6/1629906349964?sender=u4f47cdf98671301519091262&key=b10d03bf-0e27-4b05-b261-a9e535aa92c2). Let me know if you have questions or comments on that.

Does [this Checks table](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/CI-CD-Pipeline#checks) work as the items we're looking for? (Between the **Step**, **Pass Criteria**, and **Tools Used** columns, this is very clear to me, but I realize it might not be clear to everyone. If not, what do you think I should add to make it extra clear?)

Thanks!

**Comment by beechnut** [comment]
Moved to **Waiting**: waiting for project pivot work to finish before picking this up.
