### ISSUE TITLE
Design and provision AWS resources for Lambda

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#349]
**Background**

The new tech stack will use AWS Lambda as a backend. We need to figure out which AWS resources will be required to do that and work with the Cloud Foundation team to get those resources created and get access to them. 

**We'll know we're done when...**
- [x] @AdamUSDA signs off on the AWS design
- [ ] All of the designed resources exist in our development environment

**Tasks**
- [x] Research what is needed for a Lambda backend
- [x] Document the resources we will use and how they will be connected
- [x] Check with Brad Lindquist the AWS architect on the Cloud Foundation team
- [ ] Work with the Cloud Foundation team to get the resources created and made accessible

**Comment by neilmb** [comment]
https://docs.aws.amazon.com/whitepapers/latest/serverless-multi-tier-architectures-api-gateway-lambda/single-page-application.html is Amazon's documentation on how to design a Single Page App with Lambda.

**Comment by neilmb** [comment]
Setting up a Teams meeting with Cloud Foundation team to start getting these set up.

**Comment by AdamUSDA** [comment]
Hey @neilmb I like the diagram but in that process will be Mulesoft. It might be the way we authenticate with eAuth to get the single sign-on for the user.
