### ISSUE TITLE
Create a minimal Angular starter application

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#350]
**Background**

The new tech stack uses a client-side Angular application for the user interface. To get started with this, we should create an absolutely minimal "Hello, World", 200 OK version of an Angular application and get it into our code repository. We should document in a README how to run and develop the application locally.

**We'll know we're done when...**
- [ ] There is angular code in our repository that can be used for further development

**Tasks**
- [x] Research various "getting started with Angular" options
- [x] Decide on where the code lives in the repository (`/nrm_angular/`??)
- [ ] Document the local development process
