### ISSUE TITLE
Create a minimal Lambda backend

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#351]
**Background**

The new tech stack uses Lambda on the backend. We should make a minimal API on Lambda that can respond with the JSON "ok" on one endpoint. Since our Lambda application will be deployed on AWS, this will need resources from #349 as well as deployment tooling from #347.

**We'll know we're done when...**
- [ ] There is an absolutely minimal API running in our development environment

**Tasks**
- [ ] Research and decide on how our backend application will get deployed by CI/CD
- [ ] Write the world's smallest API on Lambda
