### ISSUE TITLE
Connect the Angular front end to the Lambda backend

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#352]
**Background**

In the new tech stack, the front-end application needs to communicate with the Lambda backend. Once we have finished #351 and #350 and deployed the Angular application on AWS then we should configure the Angular application to call the Lambda API and display something from the API call in the application.

**We'll know we're done when...**
- [ ] We can load our Angular application from AWS and see the resulting information that came from the Lambda API.

**Tasks**
- [ ] Research how and set up the Angular application to deploy on AWS
- [ ] Configure the Angular application with the location of the Lambda API
- [ ] Make an API call in Angular and display the result of the API call on the page
