### ISSUE TITLE
Research and document how to utilize Mulesoft

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#353]
**Background**

Mulesoft is possibly going to be available as an API integration tool. We should figure out how our individual G&A application should be involved with Mulesoft and document our findings.

**We'll know we're done when...**
- [ ] We document our findings on the Github wiki
- [ ] @AdamUSDA signs off on what we learn

**Tasks**
- [ ] Research the Mulesoft setup at FS and how it interacts with Adam's technical roadmap vis-a-vis our application
