### ISSUE TITLE
Create a plan to validate new storyboard / workflow model with people who use G&A

### ISSUE THREAD

**Issue by cmajel** [18F/NRM-Grants-Agreements#354]
**Background**
Our past research has lead us to a hypothesis of what a new G&A process may look like. This "storyboard" has helped us internally synthesize our findings and discuss what information is needed when, and who provides it.

We've walked through this with a few stakeholders, but we haven't yet shown this storyboard to people who use G&A for their reactions and adjustments. It will be particularly valuable to get feedback from budget approvers and grants management specialists, who could see the biggest changes.

This issue is to investigate and plan for a lightweight research sprint to get feedback on the storyboard and new workflow model.

**We'll know we're done when...**
- [ ] We have a testable asset and enough of a plan that we're ready to schedule sessions.

**Tasks**
- [x] Develop research plan
- [x] Develop a testable asset to get feedback on
- [x] Identify participant criteria and who we'd want to recruit
- [x] Cross check with other design work - are there complimentary topics that should be bundled with this?
- [x] Review research plan with Jay

**Comment by cmajel** [comment]
[Starting draft research plan here](https://docs.google.com/document/d/1mtz6SVjyXg6lehe2UTU9kt6_FQTahMst2kMMkp0L4wM/edit#).

**Comment by cmajel** [comment]
I have an initial plan and artifact ready for review:

* [Draft research plan](https://docs.google.com/document/d/1mtz6SVjyXg6lehe2UTU9kt6_FQTahMst2kMMkp0L4wM/edit#)
* [Draft workflow artifact to share with users](https://app.mural.co/t/gsa6/m/gsa6/1626813622927/eaad83325b5c0d4127e12f88d5d9a1ee7d1c49ee?sender=christinebath3283)

A few questions for reviewers:
* I'm leaning towards using a simplified storyboard for this activity, as it keeps things open and may encourage more discussion. Thoughts on that? 
  * We could use the more detailed workflow model, though we may want to remove some annotations for clarity.
* What research questions are missing?
* I made some suggestions on participant criteria, but I'm not sure how deep our bench is with participants. Are these reasonable criteria?

This feels like it meets the definition of done and is ready for review from @MelissaBraxton and @jayrbergjr (maybe during a coworking next week)

**Comment by MelissaBraxton** [comment]
Added some comments re: who we want to recruit in the draft. 

Re: testing assets, I don't think we should create anything new. Cognitive walkthrough is the best way I know of to validate BPMN models, and I think the current WF model in Mural is what most clearly represents the magnitude and possible impact of the change being proposed. It's also a way of getting at gaps in our knowledge re: information flow that may be more precise than what we can get via the abstract storyboard. 

I think we may learn a lot from testing the storyboard that includes sketches (but agree on removing the hypotheses and labels). I'm finding it hard to suss from the abstracted version what the major workflow changes are, and that's the main thing we want to test.

**Comment by cmajel** [comment]
@MelissaBraxton thank you for reviewing the plan. I added some follow up tasks to #360 to capture our feedback and added the sketches back into the[ testing storyboard](https://app.mural.co/t/gsa6/m/gsa6/1626813622927/eaad83325b5c0d4127e12f88d5d9a1ee7d1c49ee?sender=christinebath3283).

**Comment by MelissaBraxton** [comment]
Great! @jayrbergjr Once you have a chance to review, you can move it back to the prioritized backlog and prioritize it accordingly (In my mind it tops the backlog for UX work).

**Comment by cmajel** [comment]
@jayrbergjr we can chat at sprint planning, but I believe this is ready to close unless you have additional review you'd like to do. #360 will be the follow on ticket to iterate on the plan and actually start testing the workflow with people who use G&A.

**Comment by cmajel** [comment]
@jayrbergjr to keep the board clean I'm going to close this for now and move future work to #360; feel free to reopen if you have additional comments.
