### ISSUE TITLE
Develop means of USFS PO/PM/Tech Lead being able to track team's progress against sprint goals

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#355]
**Background**
Now that we may be moving into more of a production phase, we want to give our partners more experience with tools to help them check the teams progress toward sprint goals that they find helpful when they have a new vendor on board. 

**We'll know we're done when...**
- [ ] We've established the metrics and tool that will be useful in the near term
- [ ] We've created a new issue to capture the work of setting it up

**Tasks**
- [ ] Review metrics and reports available w/ current tools
- [ ] Make a recommendation 
- [ ] Assess any impacts on how we organize our work going forward
- [x] Create new boards or organizational structure if needed
- [ ] Revise "how we work documentation" as needed

**Comment by MelissaBraxton** [comment]
@19mderose  - I refined this a bit. Take a look and revise as you like.
