### ISSUE TITLE
Schedule sprint ceremonies

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#356]
**Background**
Now that we're kicking off with the broader USFS team, we want to make sure that the tech lead, PO, and PM can come to all of the sprint ceremonies and participate.

**We'll know we're done when...**
- [X] Sprint review/demo is scheduled
- [X] Stand ups are scheduled
- [x] We've confirmed that backlog grooming is scheduled at a time folks can participate
- [ ] We've confirmed that retros are scheduled at a time folks can participate
- [x] We've confirmed sprint planning is scheduled at a time folks can participate

**Tasks**
- [X] Review calendars, and confirm people's availability 
- [ ]  Add new folks to meetings as needed

**Comment by MelissaBraxton** [comment]
@19mderose  - It looks like Chris can attend the ceremonies at the times we have scheduled. (He's the only one not already attending) Since you are the organizer on those events, you want to add him and then close this out?

**Comment by 19mderose** [comment]
Added Chris to Sprints
