### ISSUE TITLE
Participate in vendor proposal review

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#359]
**Background**
A few folks on the team will be serving as informal advisors on the vendor review panel 7/29-7/31, and it'll consume most of our effort for about a week.  

**We'll know we're done when...**
- [x] Proposals have been reviewed 
- [x] We've shared out insights 

**Tasks**
- [x] Prep for oral demos
- [x] Attend demos and review meetings
- [x] Document recommendations / insights as needed
