### ISSUE TITLE
Conduct research and synthesis to validate and adjust proposed G&A workflow

### ISSUE THREAD

**Issue by cmajel** [18F/NRM-Grants-Agreements#360]
**Background**
In #354 we developed a plan for how we could validate and get adjustments to the proposed G&A workflow from people who do G&A work. This ticket is to execute the plan. 

**We'll know we're done when...**
- [X] We've shown the new workflow to people who do G&A work ~and have written up what we've learned.~

**Tasks**
- [x] Reach out to Melanie and Jay for recruiting leads
- [x] Revisit the plan in #354 and consider the following protocol adjustments
   - [x] Including activities around both the storyboard (for a open ended temp check) and the workflow (for a details check)
   - [x] Simplifying the workflow artifact for testing
   - [x] Adding sketches back to the testable storyboard artifact
- [x] Schedule interviews
- [x] Conduct interviews
- [x] Hold group debrief and synthesis sessions
~- [ ] Write up findings and publish to the wiki~

**Comment by MelissaBraxton** [comment]
Created #404 as a separate issue to cover write up.
