### ISSUE TITLE
Align on and document story lifecycle 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#364]
**Background**
We need to establish our shared understanding of how issues will progress through our kanban board. Output of this work will be a table [like this](https://github.com/USDAForestService/fs-open-forest/wiki/How-we-work) that lives in the wiki.

**We'll know we're done when...**
- [ ] We have a table documenting our consensus on what each of our kanban columns means, when things move in/out of each column and who is responsible for moving them. 
- [ ] Documentation [here in the wiki](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Team-practices) is up to date (currently outdated)

**Tasks**
- [x] Draft table
- [x] Circulate for review
- [x] Revise based on feedback
- [x] add revised content to [team practices wiki](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Team-practices)

**Comment by MelissaBraxton** [comment]
Drafted [here](https://docs.google.com/document/d/1OWAkHEbilnexLUJSqCmq5JXnA2gD9ahivMYdKocGCpE/edit). Awaiting final review by teammates and then posting to wiki.

**Comment by 19mderose** [comment]
Complete. Need help in adding to Wiki.

**Comment by 19mderose** [comment]
Added table to wiki describing our sprints.
https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Team-practices
