### ISSUE TITLE
Finalize team charter

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#365]
**Background**
Split off of #346 re: "how we work." 

**We'll know we're done when...**
- [ ] We've documented our team charter as a team
- [ ] Charter is available to all in Box

**Tasks**
- [ ] Draft team charter async
- [ ] Review as a team
-[ ]  post to Box
