### ISSUE TITLE
As someone creating a new proposal, I’d like basic information about the proposal to be persistent on every page so that I don’t lose track of what I’m working on.

### ISSUE THREAD

**Issue by cmajel** [18F/NRM-Grants-Agreements#369]
**Notes**
One of our current design hypotheses is that breaking the proposal creation process into a series of shorter, stepped forms will make the proposal creation process clearer and less confusing. [In testing this](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/User-research-report-Sprint-7,-May-2021), we suggested testing a persistent header that includes workplan ID and cooperator name to make it clearer which proposal a person is working on.

This issue is to explore header iteration in the proposal creation flow to give PMs necessary context and reference information as they enter their proposal information. 

**We'll know we're done when...**
- [ ] We have an updated mock up that we can test with people who use G&A, and they find the header information necessary and useful

**Supporting documentation**
- [ ] [May 2021 research report](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/User-research-report-Sprint-7,-May-2021)

**Open questions**
- [ ] What information do PMs need to identify which proposal they are working on

**Tasks**
- [ ] Create updates mocks/prototypes
- [ ] Review with Jay
- [ ] Schedule to be included in future usability test
- [ ] What else?

**Comment by cmajel** [comment]
@MelissaBraxton added this based on our chat last week. A few questions:

- In the research report, I see this recommendation but I'm not sure which findings it came from. Can you say more about which observations feel most supportive of this change?
- Is this tagged correctly for an issue that is low priority, but could be included in future 18F / vendor design work?

**Comment by MelissaBraxton** [comment]
@cmajel  - There were a few comments from users re: wishing they could see the **workplan ID** and **cooperator name** at more than one step in the process. (e.g., "I like seeing the workplan ID here, but I'd also like to see it earlier or at a different step...")

Re: prioritization, I could def see bringing this in to a near term sprint. @jayrbergjr?

**Comment by jayrbergjr** [comment]
I agree especially if we start focusing on design and development work again.
