### ISSUE TITLE
Stakeholder influence map

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#37]
**Background**

There are lots of stakeholders involved in this NRM G&A project from NRM, OG&A, USFS OCIO, USDA OCFO, etc. As an artifact, a stakeholder influence map will be helpful to 18F in upcoming engagements but also to everyone at FS to help them keep track of the relevant individuals (who they may or may not be aware of).

**Acceptance criteria** 
- [x] 18F team members review and accept
- [x] One or more USFS contacts review and agree

**Tasks**
- [x] Compile a list of stakeholders
- [x] Locate stakeholders on the interest/influence quad chart

**Definition of done**
- [X]  Meets acceptance criteria
