### ISSUE TITLE
Refine Vision from Workshop Visioning Exercise

### ISSUE THREAD

**Issue by jayrbergjr** [18F/NRM-Grants-Agreements#370]
We need to take all the work done on the visioning exercise and incorporate team's working mural into an updated vision.  **Background**

**We'll know we're done when...**
- [ ] We have sent out an updated Vision and everyone approves.
- [ ] 

**Tasks**
- [ ] Review the mural work
- [ ] Ensure that Enterprise Solution is part of the vision
- [ ] incorporate themes and high points into the vision

**Comment by jayrbergjr** [comment]
Check in with Chris C. to ensure we are ok to add "enterprise."

**Comment by jayrbergjr** [comment]
At G&A weekly check in (8/11) we talked through CIO working the "enterprise" issue.  CIO leadership still talking  through it, then CIO and BusOps senior leaders will have to work out what the vision for "enterprise" consist of for this project.
