### ISSUE TITLE
As a program manager creating a proposal, I need to indicate the program category so that budget approvers and GMSs have the context they need to review my proposal

### ISSUE THREAD

**Issue by cmajel** [18F/NRM-Grants-Agreements#376]
**Notes**
During a recent design review, we discovered that the `program category` field was dropped from the mockup. 

This field should be added back in, because:

* We believe PMs (who are creating proposals) know their program category
* Program category is needed by GMSs and Budget approvers to verify if the program and funding source are aligned.
* System administrator should be able to add/remove programs easily. 

**We'll know we're done when...**
- [ ] PM can select from the list of programs.
- [ ] System administrator (WO OG&A Policy - Systems team) can add and remove programs

**Supporting documentation**
- [ ] 

**Open questions**
- [ ] What kind of reports are run from this data?
- [ ] Not a question but a note. We've heard this is more useful as a single select; its currently a multi select. We should talk with PMs to verify that they could switch to a single select and document cases when a multi select is needed.

**Tasks**
- [ ]

**Comment by MelissaBraxton** [comment]
Re: note from @jayrbergjr  - This issue may need to be revised to reflect that this meets upward reporting needs, but is not required by GMS or BAs to understand funding alignment.
