### ISSUE TITLE
Document how to use and agreement creation workflow and data map in the wiki 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#379]
**Background**
Re: success scenario 16 _The G&A office onboards a new vendor. Vendor designers are able to easily access design files and documentation to quickly be able to pick up where the 18F team left off._

**We'll know we're done when...**
- [x] The data mapping sheet, agreement creation WF, and documentation can be easily understood by designers unfamiliar to the project
- [x] The data mapping sheet, model, and documentation can be easily accessed from a central design resource hub

**Tasks**
- [x] Write documentation explaining how the data mapping sheet and model can be used; ensure they include context that makes them understandable as stand alone artifacts
- [x] Test understandability with an 18F design peer unfamiliar w/ the project
- [x] refine based on feedback
- [x] Upload sheet and/or link to model from the repo

**Comment by MelissaBraxton** [comment]
@jayrbergjr - this is one of the new design documentation issues I mentioned to think about prioritizing.

**Comment by MelissaBraxton** [comment]
@cmajel - based on your peer review today, can we close this out?

**Comment by cmajel** [comment]
It's looking great! I updated the sidebar link and added a table of context to the [timeline of design activities](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Timeline-of-design-activities) with anchor links to help with the `summary` issue. 

Could you give these a look over and edit as needed? If they look good to you then we're good to close out!
* [Added a section to design approach](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Our-design-approach) about our cadence
* Added [this page on roles and recruitment criteria](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Roles-and-recruiting-criteria)

**Comment by cmajel** [comment]
Whoops - realize my comment here is not related to this part of the wiki 😅 . So yes, looks good and will close out!

[Link for posterity ](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Timeline-of-design-activities#june-aug-2021-ga-workflow-and-storyboard)
