### ISSUE TITLE
Update the GitHub wiki

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#38]
**Background**

**Acceptance criteria** 
- [x] GitHub wiki is up to date

**Tasks**
- [x] Upload topline
- [x] Link to User journey
- [x]  Update problem statement
- [x] Update background
- [x] Update roles
- [x] Update team practices

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by allisonnorman** [comment]
[Doc where I'll draft](https://docs.google.com/document/d/1BcUU5TQRJofIRqi5DSojlBJL5pbjx125ADvFNgbaXrs/edit#heading=h.pve3ayr6wmp5)

**Comment by allisonnorman** [comment]
Done for now but let's keep this updated as we go!
