### ISSUE TITLE
Document how to use the storyboard in the wiki 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#380]
**Background**
This issue covers work needed to ensure that vendor designers have the right springboard for their work when they come on board. It maps to success scenario 16 in our transition plan:

_The G&A office onboards a new vendor. Vendor designers are able to easily access design files and documentation to quickly be able to pick up where the 18F team left off._ 

**We'll know we're done when...**
- [ ] The storyboard can be easily understood by designers unfamiliar to the project
- [ ] The storyboard can be easily accessed from a central design resource hub

**Tasks**
- [x] Clean up the storyboard; ensure it includes context that makes it understandable as a stand alone artifact
- [x] Test understandability by having an 18F peer designer unfamiliar to the project review
- [x] upload and/or link to it in the wiki

**Comment by MelissaBraxton** [comment]
Another design documentation issue, @jayrbergjr

**Comment by MelissaBraxton** [comment]
@cmajel  - Based on your peer review today, can we close this out?

**Comment by cmajel** [comment]
Yes I think we can!

[Adding a link to the recap on this for posterity](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Timeline-of-design-activities#june-aug-2021-ga-workflow-and-storyboard).
