### ISSUE TITLE
Write guidance for new designers on how to begin working with our design files

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#381]
**Background**
Re: success scenario 16 _The G&A office onboards a new vendor. Vendor designers are able to easily access design files and documentation to quickly be able to pick up where the 18F team left off._

**We'll know we're done when...**
- [x] How to pick up where we left off with our design files can be easily understood by designers unfamiliar to the project
- [x] Design files can be easily accessed from a central design resource hub

**Tasks**
- [x] Clean up and contextualized design files 
- [x] Write wiki guidance on getting started using design files.
- [x] Test Figma file cloning and integration with other design tools, and include in documentation.
- [x] Test understandability with an 18F design peer unfamiliar w/ the project
- [x] refine based on feedback
- [x] Upload or link files to the repo

**Comment by MelissaBraxton** [comment]
@cmajel  - I'm imagining you'll be taking the lead on this, so take a look and refine as needed. (cc @jayrbergjr )

**Comment by cmajel** [comment]
Love this: `Test understandability with an 18F design peer unfamiliar w/ the project`

I added a task to test the Figma > other tool compatibility and a language tweak from upload files > upload or link files. I'm thinking about how we won't know what tools the vendor has experience in, and I'm leaning towards keeping them Figma files and making them publicly viewable. This would let anyone access (and I believe clone) with a free Figma account. Figma does have community tools for converting to Sketch and XD, which I can test.

**Comment by cmajel** [comment]
Sharing some notes for initial feedback:
* Started some [wiki drafts](https://docs.google.com/document/d/1P_F2SHZeS84zpy8i9b75GKDQTUhzHgX7256x5a1H68w/edit#) here
* In addition to organizing and cleaning up files, for each "page" (aka, design exercise),  I'm adding a cover sheet to recap what we did for each round of work. Here's an example - feedback welcome on things we should add or adjust.
![design-recap--1 dashboards](https://user-images.githubusercontent.com/2374206/130146762-5764f97a-d1e3-4a6e-95b0-bb4e1a2299cc.png)

* I experimented with some Figma <> Sketch tools and have run into an issue with a common converter. I'll continue to troubleshoot and inventory tools that a future team can use.  I'll also note that we don't know which tools the team will be using and our work is more exploratory than set guidance for the future, so I believe the value of these assets may be more for understanding our work than as a file to start working on. 

This work will extend into the next sprint. cc @MelissaBraxton for visibility.

**Comment by cmajel** [comment]
This is now live on the wiki!

I've made a read-only version of our [Figma file publicly viewable](https://www.figma.com/file/AOWq8IWGSAUGZiqZ1nZSeF/USFS-Grants-and-Agreements-Playground?node-id=804%3A0) so that future teams can copy and work from it. I've also noted in [the design tools section of the wiki](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Design-tools) more detail on how we built the file and it's limitations.
