### ISSUE TITLE
Document known design debt in wiki

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#382]
**Background**
Re: success scenario 16 _The G&A office onboards a new vendor. Vendor designers are able to easily access design files and documentation to quickly be able to pick up where the 18F team left off._

**We'll know we're done when...**
- [x] Our known design debt and known unknowns are documented in the central hub for onboarding new designers 

**Tasks**
- [x] Document known design debt and known unknowns /areas for further discovery in the wiki
- [x] Peer review
- [x] Refine based on feedback

**Comment by cmajel** [comment]
I've started a [rough scratchpad with design debt notes](https://docs.google.com/document/d/14C5neV7rClnoGX2ds7ZBEOXYB6qwzrW-QrOeBxewGp8/edit#) that are coming up as I clean up design assets (#381). Edits and half-formed thoughts welcomed.

cc @MelissaBraxton

**Comment by MelissaBraxton** [comment]
@cmajel - Added! Can we close this out?

**Comment by cmajel** [comment]
Yes! I updated the sidebar link and it's looking great 🙂 

[Adding a link to this page for posterity](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Known-design-debt).
