### ISSUE TITLE
Prepare materials to use in onboarding vendor designers. 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#383]
**Background**
Re: success scenario 16 _The G&A office onboards a new vendor. Vendor designers are able to easily access design files and documentation to quickly be able to pick up where the 18F team left off._

**We'll know we're done when...**
- [ ] We feel confident that executing the vendor onboarding plan will ensure that vendor designers have what they need to pick our design work where we left off

**Tasks**
- [ ] Plan how and where we'll cover UX Research and Design onboarding during the vendor kick off week
- [ ] Draft meeting agendas, slide decks, READMEs, etc. that facilitate knowledge transfer from 18F to vendor designers.

**Comment by cmajel** [comment]
Relates to #386 and #385
