### ISSUE TITLE
18F gives opportunities for the product owner to review our work as they would a vendor 

### ISSUE THREAD

**Issue by cmajel** [18F/NRM-Grants-Agreements#384]
**Background**
Re success scenario 3: _NRM has hired a new vendor using modern, best practices for performance based service contracting (including 18F’s software delivery based quality assurance plan). The vendor team is skilled in working in human centered design and in an agile, iterative fashion._

We want the G&A team to have experience reviewing design and technical work before a vendor comes on board. This ticket is to build in more review practices in our sprint cadence.

**We'll know we're done when...**
- [ ] Jay has multiple experiences reviewing design/technical work before it is closed and accepted
- [ ] Jay demonstrates proficiency in asking questions that (1) ensure the work is heading in the right direction and (2) that contribute to his clear understanding of what has been / is being built. This includes asking for explanations and demos, and asking about testing and documentation.

**Tasks**
- [ ] Schedule a design review / feedback session to review items ready to be closed for the sprint
- [ ] Schedule a code review / feedback session to review items ready to be closed for the sprint

**Comment by cmajel** [comment]
Noting that we have done a few design reviews with Jay and Jamie in past sprints.

**Comment by cmajel** [comment]
@beechnut flagging this for you since I know you've been working on some of this. Please feel free to review and edit if there are specific activities you are planning.

**Comment by beechnut** [comment]
@cmajel Thank you, just added a lengthy success criterion.
