### ISSUE TITLE
Consult on RACI Chart for decision-making

### ISSUE THREAD

**Issue by beechnut** [18F/NRM-Grants-Agreements#387]
**Background**
Heather Busam asked 18F to produce a complete [RACI chart](https://www.planstreetinc.com/raci-chart/) for this project, in part to clarify decision-making between the CIO and Business Unit.

In a 1:1, @neilmb and @beechnut agreed on the following proposed scope of work.

**The 18F team can consult on this process by:**

- running a workshop with relevant stakeholders
- coaching

**The 18F team cannot / will not:**

- construct & own a RACI chart that claims to be authoritative
- resolve (adjudicate or mediate) any differences that arise
- take responsibility for organizing / coordinating dialogues

**We'll know we're done when...**
- [ ] We have supported/coached the relevant org units to their satisfaction

**Tasks**
- [ ] Sync with 18F accounts to inform about this work
- [ ] Sync with Heather on the scope of work

**Comment by aaronburk** [comment]
this may be useful ?? it is form Open Forest 
[ePermit RASCI Chart_V0.3_stakeholderorgsadded_5_25__18.xlsx](https://github.com/USDAForestService/NRM-Grants-Agreements/files/6971210/ePermit.RASCI.Chart_V0.3_stakeholderorgsadded_5_25__18.xlsx)

**Comment by jayrbergjr** [comment]
We do this first then Visioning. #370
