### ISSUE TITLE
Product framing

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#39]
**Background**
As we align on the scope of M1, M2, and M3, and the next focus area for E&I prototyping, we need to work with Jay to begin framing this work. How we talk about the work we do will be important for communicating with stakeholders, and ultimately the vendor. Product framing is an evolving process, and as we learn more, we will update 

**We'll know we're done when...**
(Product framing is never really _done_, but we can close this issue when...)
- [X] We have a shareable version of a product framing doc finished. 
- [X] We have published to the wiki. 

**Tasks**
Pair with Jay to:
- [x] Finalize roadmap [milestones](https://docs.google.com/document/d/1s8TwI5bfuhLAEVgs4VAc6g-yPWnGQAh59CaztU7jst0/edit#) and add to roadmap
- [X] Expand roadmap milestone framing [doc](https://docs.google.com/document/d/1s8TwI5bfuhLAEVgs4VAc6g-yPWnGQAh59CaztU7jst0/edit#) to incorporate other product framing components
- [X] We've framed the E&I focus area (either within the same doc or separately)
- [X] Think about other ways to visualize the roadmap (text, other visuals) for an executive-level summary view into the work
- [X] Talk about how/when this gets updated as we learn more. 
- [X] Get feedback from team.
- [X] Publish to wiki.

**Comment by allisonnorman** [comment]
[WIP draft](https://docs.google.com/document/d/1k-lgrzYcLBtq4uSNirK5Umh5prYGUvglhp7ni_NdkZE/edit#heading=h.g751455g5lfd)

**Comment by allisonnorman** [comment]
Framing references on wiki: 
- https://github.com/18F/NRM-Grants-Agreements/wiki/Product-roadmap
- https://github.com/18F/NRM-Grants-Agreements/wiki#background
