### ISSUE TITLE
Set up USWDS

### ISSUE THREAD

**Issue by jayrbergjr** [18F/NRM-Grants-Agreements#392]
**Background**
Get the design system into the app early to be the foundation for rapid prototyping.  

**We'll know we're done when...**
- [x] The elements in existing prototype conform to USWDS style
- [x] The list of grants looks like a table or standard USWDS list

**Tasks**
- [x] Add style and JS into Angular build pipeline
