### ISSUE TITLE
Feature: grant navigation and detail view

### ISSUE THREAD

**Issue by beechnut** [18F/NRM-Grants-Agreements#399]
**Background**
We want to lay the minimal groundwork for the app, which involves listing grants, allowing some search, and showing grant details.

Do we want this issue to include things like table/list pagination, typeahead filtering, and/or a grant view page?

**We'll know we're done when we have...**
- [ ] A table of grants, sorted by most recently updated first
- [ ] Pagination on the grants table
- [ ] Grant "detail" view, listing all grant details in the database
- [ ] Links to navigate back to list
- [ ] Tests to cover grants list, initial ordering, grant view.

**Tasks**
- [ ] Set up tests
- [ ] Add initial sort to table from #388 
- [ ] Add pagination
- [ ] Set up grant detail view
- [ ] Set up navigation
