### ISSUE TITLE
Map team activities to path analysis goals 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#4]
**Background**
We want to make sure we are being purposeful about how we spend our energy and remain focused on work that gets us closer to the project goals. To this end, we'll fill in [this sheet](https://docs.google.com/spreadsheets/d/1zezFX2Qz-Gbh9eoZbg-mT6g0zNmzALxHV33DoejGYJ8/edit#gid=209839417).

**Acceptance criteria** 
- [x] We've broken down our project goals and mapped them to high-level research questions 
- [x] We have a high level plan for how we'll get the information we need
- [x] We have consensus on the approach we will take

**Tasks**
- [X] Schedule co-planning session
- [X] Create co-planning exercise in Mural
- [x] Run Mural session
- [x] Attach rough target dates for when we want to have gathered info
- [x] Melissa writes up new issues to get us started
~- [ ] Asynchronously fill in [PA mapping sheet](https://docs.google.com/spreadsheets/d/1zezFX2Qz-Gbh9eoZbg-mT6g0zNmzALxHV33DoejGYJ8/edit#gid=209839417)~

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
[Mural](https://app.mural.co/t/gsa6/m/gsa6/1605566466024/b0d5b3e8e751df520a10d4ae4275ad6415740703) for brainstorming on this
