### ISSUE TITLE
Final report / package

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#40]
**Background**

**Acceptance criteria** 
- [x] Report clearly lays out recommendations
- [x] Report describes next steps, near term, mid term, and long term at a high level
- [x] Report includes a way to easily navigate to other things we've delivered. 

**Tasks**
- [x] Schedule co-working on outline and structure
- [x] Assign sections and write
- [x] Edit/review/refine async
- [x] co-work/review
- [x] Have someone from writing lab edit
- [x] Send to partners for review

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Add sections on colab w/ QSMO and TMF.
