### ISSUE TITLE
Feature: grant search

### ISSUE THREAD

**Issue by beechnut** [18F/NRM-Grants-Agreements#400]
As someone who works with grants, I want to be able to search for a specific grant.

**We'll know we're done when...**
- [ ] Typing in the search field above the grants list instantly filters grants by any displayed grant attributes
- [ ] We can click on a grant, go back to the list, and have the search be persisted.

**Tasks**
- [ ] Add a search field
- [ ] Write tests for grant search
- [ ] Set up grant search
- [ ] Write tests for navigation persistence
- [ ] Set up navigation
