### ISSUE TITLE
Write up workflow research insights

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#404]
**Background**
This issue is to document what we learned in our workflow research. (#360 )

**We'll know we're done when...**
- [ ] insights are documented in wiki
- [ ] refinements are documented as user stories 

**Tasks**
- [x] Synthesize
- [x] Write up
- [x] Get one other person on team to review
- [ ] Post to wiki
- [x] Add user stories to user story sheet

**Comment by MelissaBraxton** [comment]
@jayrbergjr [draft](https://docs.google.com/presentation/d/1TgURKlZaNAwLOGNeDVuR-2E9EPhC9FYRQHfnKauqH0c/edit#slide=id.g118c086a31_0_21) for you to review after the holiday!

**Comment by cmajel** [comment]
@MelissaBraxton per our chat yesterday this looks good for peer review ✅
