### ISSUE TITLE
Define & document initial workflows in each environment

### ISSUE THREAD

**Issue by beechnut** [18F/NRM-Grants-Agreements#407]
**Background**
We would like to have a workflow diagram of each environment so that we can walk through the DevOps process in all environments.

**We'll know we're done when...**
- [ ] We have clear written definitions of `sandbox`, `development`, `test`, `staging`, and `production` environments are used for.
- [ ] We have documentation of the resources attached to each environment.
- [ ] We have a diagram of the automatic & manual test/QA processes in each environment.

**Tasks**
- [ ] Create a new diagram that shows the workflow for each environment
- [ ] Meet to determine what kinds of tests need to be run. (May need to be general, as we won't necessarily know all QA processes until features are developed.)

**Comment by neilmb** [comment]
This is going to be preparatory work for #309, to define the environments before we set them up.
