### ISSUE TITLE
Review & decide on a serverless framework

### ISSUE THREAD

**Issue by beechnut** [18F/NRM-Grants-Agreements#408]
**Background**
We want to select a serverless framework so we don't have to change it later during application development.

Criteria include:

- general capabilities and limitations
- how they work with API Gateway
- how they work in different environments 

**We'll know we're done when...**
- [ ] We have approved an ADR deciding on a serverless framework that researches Serverless, Claudia.js, SAM, and any other viable candidates.

**Tasks**
- [ ] Draft an ADR with initial research
- [ ] Have team members review the ADR, add research, etc.
- [ ] Approve the ADR

**Comment by beechnut** [comment]
Note that this shouldn't be a blocker to completing #347—Claudia.js is two small files and one line of code (`npm run update`), so can be swapped out easily.
