### ISSUE TITLE
Orient Jay to Product Owner role

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#41]
**Background**
We want to have an initial meeting with Jay to orient him to the PO role and help him know what to expect. 

**Acceptance criteria** 
- [x] Jay has been oriented to the role and knows what to expect in. the coming weeks. 

**Tasks**
- [x] Email USDA's BMO to find out about upcoming PO training
- [x] Create new issue for onboarding Jay
- [x] Draft agenda for mtg
- [x] Create PO tickler system/calendar specific to Jay
- [x] Prep product heuristics doc. 
- [x] Review w/ Jay

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
AGENDA
 - Review scrum overview
 - Review sprintly PO schedule
 - Review heuristics doc. 


Review deep dive schedule over the weeks.

**Comment by MelissaBraxton** [comment]
Removed scrum overview deck, since I think we'll save it as a separate deep dive topic.
