### ISSUE TITLE
Update org chart Mural

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#413]
**We'll know we're done when...**
- [ ] Our org chart Mural reflects our current understanding of FS org and relationships

**Tasks**
- [ ] Update [Mural](https://app.mural.co/t/gsa6/m/gsa6/1630607943667/66b9992b43d5f486e40be34169001278c4f59477?sender=melissabraxton2796)
- [ ] Share w/ team for review
