### ISSUE TITLE
Update GitHub content to better contextualize where we are w/ this work (re: project pivot, etc.)

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#414]
**Notes**

**We'll know we're done when...**
- [x] People unfamiliar with the project can easily understand the current status and what's next. 

**Tasks**
- [x] Update README
- [x] Update wiki home page
- [x] Update roadmap section of the wiki
