### ISSUE TITLE
Plan and deliver final presentation

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#42]
**Background**

**Acceptance criteria** 
- [x] Final presentation shares where we ended and tees up partners to make decisions. 

**Tasks**
- [x] Melissa To schedule final presentation
- [x] Draft deck

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Add another layer to our recommendations on how to pursue our recommendation: working with HHS and applying for TMF
