### ISSUE TITLE
Onboard Jay to Product owner role

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#43]
**Background**
We'll be getting Jay started in the Product Owner role as we get going on the E&I. During the E&I, we'll focus on helping Jay get more hands on experience with a cross-functional agile team as well as diving deep into product framing and other product topics. The work will be a bit different than when we have a vendor on board that is actually shipping code each sprint, but we'll use this time in the E&I to help USFS be ready to hit the ground running with a vendor in a few months.

**Acceptance criteria** 
- [x] PO has sufficient context / background and access to tools that they need to begin working with the team
- [x] PO feels confident re: what to expect in the near term

**Tasks**
- [x] Have onboarding mtg to discuss PO role
- [X] Send email to Jay asking about availability for a sync this week
- [x] Invited to Slack? 
- [x] Review any research reports to date

**Allison/Jay 1st sync**
- [X] Intro to GitHub
- [X] What docs can/can't Jay access? (Can he access Gdocs? GACA? Mural?)
- [X] Talk through sprint 1 stories
- [X] Set up recurring Product Owner mtgs w/ Jay

**Next:** 
- [x] Figure out GSuite access (GACA?)
- [x] Added to team calendar events/meetings starting 2/22 (will do after team charter sync)
- [x] Add Jay to GH repo
- [x] Share project folder
- [x] Deeper dive on GH once he has access

**Comment by allisonnorman** [comment]
This is a work in progress obviously but closing as we have sufficiently onboarded Jay to the tasks set out.
