### ISSUE TITLE
Onboard Allison

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#44]
**Acceptance criteria** 
- [x] They have access to all tools and info they needs
- [x] They have read enough background material to feel confident getting started on the project

**Tasks**
- [X] Melissa adds them to GitHub
- [x] Review NRM technical PA final reports
- [x] Review topline report
- [x] Review solutions trade off doc
- [x] Review final report draft
- [x] Review user role descriptions and journey map
- [x] Review midpoint check in deck
- [x] Allison has been added to the GH G&A team 
- [x] Allison has been added to all relevant Slack channels
- [x] Credentialing process has begun
- [x] Review user research and other docs in drive

**Definition of done**
- [x]  Meets acceptance criteria
