### ISSUE TITLE
Onboard Carter

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#45]
**Acceptance criteria** 
- [x] They have access to all tools and info they needs
- [x] They have read enough background material to feel confident getting started on the project

**Tasks**
- [x] Melissa adds them to GitHub
- [x] Review NRM technical PA final reports
- [x] Review topline report
- [x] Review solutions trade off doc
- [x] Review user role descriptions and journey map
- [x] Review final report draft
- [x] Review midpoint check in deck
- [x] Has been added to the GH G&A team 
- [x] Has been added to all relevant Slack channels
- [x] Credentialing process has begun

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by tbaxter-18f** [comment]
@MelissaBraxton I believe the last boxes can be checked off and we can close this out, but you'd know better than I would.
