### ISSUE TITLE
Onboard Christine

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#46]
**Acceptance criteria** 
- [x] They have access to all tools and info they needs
- [x] They have read enough background material to feel confident getting started on the project

**Tasks**
- [x] Melissa adds them to GitHub
- [x] Review NRM technical PA final reports
- [x] Review topline report
- [x] Review solutions trade off doc
- [x] Review final report draft
- [x] Review user role descriptions and journey map
- [x] Review midpoint check in deck
- [x] Donny has been added to the GH G&A team 
- [x] Donny has been added to all relevant Slack channels
- [x] Credentialing process has begun

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by cmajel** [comment]
@MelissaBraxton moving this to done!
