### ISSUE TITLE
Draft E&I team charter

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#47]
**Background**
AS a team, we want to make sure we have conensus on how we want to work together. 

I created a copy of the PA team's charter that we can use as a starting point [here](https://docs.google.com/document/d/1Mwx3pe9tYSNWga-gBVWmNcdbzS5pk_l7bWIK3oNyGXc/edit#heading=h.5inahibqieal), but let's all dive in and edit until it really reflects the way we want to work. 

**Acceptance criteria** 
- [x] We have team charter that describes our desired working and communication practices
- [ ] We have a team charter that clearly delineates each of our roles on the project

**Tasks**
- [x] Allison reviews draft team charter async
- [x] Carter reviews draft team charter async
- [x] Christine reviews draft team charter async
- [x] Schedule charter co-working
- [x] Team co-working to refine the charter until everyone is happy with it 

**Definition of done**
- [x]  Meets acceptance criteria
