### ISSUE TITLE
Map E&I plan to goals/desired outcomes

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#48]
**Background**
We want to make sure we are being purposeful about how we spend our energy and remain focused on work that gets us closer to the project goals. To this end, we'll go through a planning exercise in Mural. You can find the ourput of a similar activity for the PA [here](https://app.mural.co/invitation/mural/gsa6/1605566466024?sender=melissabraxton2796&key=91d79188-04d0-4726-8eb6-c9a788087083)

**Acceptance criteria** 
~- [ ] We've broken down our project goals and mapped them to high-level research questions~ 
- [x] We have a high level plan for how we'll get the information we need
- [x] We have consensus on the approach we will take

**Tasks**
- [X] Schedule co-planning session
- [x] Create co-planning exercise in Mural
- [x] Run Mural session
- [x] Attach rough target dates for when we want to have gathered info
- [x] Melissa (or Allison?) writes up new issues to get us started

**Definition of done**
- [X]  Meets acceptance criteria
