### ISSUE TITLE
Draft modernization cookbook feedback for mtg with Sue on Wed. 11/18

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#5]
**Background**
We want to provide suggestions to NRM on how they can refine their draft modernization cookbook to better meet their goals. At a high level, the goals of the doc are to:
* provide business units with a concise description of how the roles and team required and how they'll partner with NRM as they modernize
* reinforce a partnership, rather than a customer service, dynamic between NRM and the business
* Embrace current thinking on how to approach modernization generally. 

**Acceptance criteria** 
- [x] We have communicated to NRM how they should refine their modernization plan to minimize risks of project failure 
- [x] Communication is tailored to our audience

**Tasks**
- [x] Review marked up draft cookbook
- [x] Revise how feedback is communicated
- [x] Write up a summary of key feedback points
- [x] Share with Sue in advance of meeting

**Definition of done**
- [x]  Meets acceptance criteria
