### ISSUE TITLE
Plan and schedule CIO presentation

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#54]
**Background**

**Acceptance criteria** 
- [x] Includes all relevant stakeholders
- [x] Presentation delivered

**Tasks**
- [x] Schedule time
- [x] Draft outline
- [x] co-work on deck / assign sections
- [x] team review/refine

**Definition of done**
- [x]  meets acceptance criteria
