### ISSUE TITLE
Draft high-level research questions that map to E&I planning

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#56]
**Background**

**Acceptance criteria** 
- [x] Research Qs live in an easily accessible place for all on the team

**Tasks**
- [X] Co-work on initial brainstorm
- [x] Identify Qs we want to answer and a a starting point for how we hope to answer them

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Started a research scratch pad here: https://docs.google.com/document/d/1M7P7YxvvIAG8rdDmSq8VRmdTfl4YxAxEo4eouYjohWQ/edit#heading=h.yg76hqda79nm
