### ISSUE TITLE
 Understand prototyping environment options

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#57]
**Background**
As we start to think about opportunities to prototype in order to de-risk the modular approach technically, we should understand what options we have and what blockers we may face. We may not be in a position to get started on prototyping yet, but we should know what limitations might exist and pave a path in the meantime. 

[Link to Mural](https://app.mural.co/t/gsa6/m/gsa6/1613157695375/011b2f3d4b2275d948401e7153dac71bb0d8448a) research questions

Side goal from our [E&I planning Mural](https://app.mural.co/t/gsa6/m/gsa6/1612470069350/7b4b7b17d33ed20f7c1a396f26a193565e86997c): how can we make cloud native feel more safe? 

**Acceptance criteria** 
- [ ] We know what platforms are available for us to use
- [ ] We have approval/OK to proceed down a particular path (when applicable)

**Tasks**
- [ ] Start thinking about what permissions or access issues that are going to come up and who we can work those out with. (Also, who will handle approvals for prototyping?)
- [ ] Ask for a list of available/approved platforms from IT stakeholders
- [x] Find out if we can prototype on cloud.gov
- [x] Get a database dump from NRM to enable our prototyping work

**Definition of done**
- [ ] Meets acceptance criteria

**Comment by tbaxter-18f** [comment]
In meeting, we determined our current architecture is fine, and Jay will handle approvals. So I think we've resolved all of this now.

**Comment by MelissaBraxton** [comment]
USFS already has an agreement w/ cloud.gov for Open Forest and are well below the usage threshold. (May be notable, Open Forest is just about to migrate to AWS, but the Cloud.gov agreement goes through June 2021.)

**Comment by tbaxter-18f** [comment]
Also,  Cloud offers no-cost prototyping sandboxes. 

Given that we worked through this in the meeting yesterday, i'm going to go ahead and close it out as done. If anyone disagrees, of course, please feel free to re-open!
