### ISSUE TITLE
Understand and document the data structure and taxonomy of agreements

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#58]
**Background**
As we plan for potentially prototyping a modular approach technically, and start to think about a first thin slice, we want to understand the data better in order to identify opportunities and to get more familiar with how things work today. 

[Link to Mural](https://app.mural.co/t/gsa6/m/gsa6/1613157695375/011b2f3d4b2275d948401e7153dac71bb0d8448a) with key research questions.

Note: We should talk about how deep we go here in order for this to be valuable and realistic for where we are in this project. 

**We'll know we're done when...**
- We've validated our understanding of what kinds of grants and agreements live in the application now.
- We've created a home to document what questions we have about the current data structure, which we have in our [NRM tables spreadsheet](https://docs.google.com/spreadsheets/d/1szcS652FZohhxkSPMNGnkPrj06uxSKqvC3ClL83ngsk/edit#gid=0)
- We know enough about the db structure that we know what to ask for when we decide on a first slice ([ERD]( the ERD does this.) may be enough)

**Tasks**
- [x] Dig into the data structure of an agreement
    * [FS NRM tables spreadsheet](https://docs.google.com/spreadsheets/d/1szcS652FZohhxkSPMNGnkPrj06uxSKqvC3ClL83ngsk/edit#gid=0)
    * [G&A ERD]( https://drive.google.com/file/d/12NhtYtTt1Vt-E95poEtvN2d4VG7TxyuJ/edit)
- [x] Dig into the taxonomy of agreements
    * [Mapping of agreement types from prior research](https://docs.google.com/spreadsheets/d/1lqBLtuF_K2LhoWDt0E9HGhRNLGn5We8z/edit#gid=576964291)
- [x] Review and update the instrument and attachment mapping with Jay or Jamie (or maybe at workshop?) to verify we know the universe of agreement types
   * Met with Jamie and team on 3/19 to update the spreadsheet. Also received some helpful guidance from them on [DB fields and what's required by the current system vs business](https://drive.google.com/drive/folders/1oOQpnH6G7u23qxB9bzXI1ZHJ9lc-Kgil).
- [x] Set up time with Jamie to review open grants table questions.

**Comment by tbaxter-18f** [comment]
Related: #69 

Link to ERD: https://drive.google.com/file/d/12NhtYtTt1Vt-E95poEtvN2d4VG7TxyuJ/edit

**Comment by cmajel** [comment]
@neilmb @tbaxter-18f [This instrument mapping sheet](https://docs.google.com/spreadsheets/d/1lqBLtuF_K2LhoWDt0E9HGhRNLGn5We8z/edit#gid=1614149300) from past research was helpful context for me on this. This maps type of agreements to the forms needed (not sure how current it is)

**Comment by allisonnorman** [comment]
We talked about reconciling this issue with #69 in stand. I've pulled out the technical details from this issue there, and adjusted this issue to reflect the ongoing efforts to understand the columns in the db and reconciling that with the research. @cmajel Since you've been working on this, I'm going to assign this to you.

**Comment by cmajel** [comment]
@allisonnorman I feel like this ticket is really big and could run the whole project 😅 . I've added some resources to the description to document what we have so far in this space.

I see the goals of this right now to...
* Validate our understanding of what kinds of grants and agreements live in the application now.
* Create a home to document what questions we have about the current data structure, which we have in our [NRM tables spreadsheet](https://docs.google.com/spreadsheets/d/1szcS652FZohhxkSPMNGnkPrj06uxSKqvC3ClL83ngsk/edit#gid=0)  
* Know enough about the db structure that we know what to ask for when we decide on a first slice, and I feel like [the ERD](https://drive.google.com/file/d/12NhtYtTt1Vt-E95poEtvN2d4VG7TxyuJ/edit) does this.

I see the next step here as.. 
* [reviewing and updating the instrument and attachment mapping](https://docs.google.com/spreadsheets/d/1lqBLtuF_K2LhoWDt0E9HGhRNLGn5We8z/edit#gid=576964291) with Jay or Jamie (or maybe at workshop?) to verify we know the universe of agreement types
* setting up time with Jamie to review open `grants` table questions. 

Does this feel right to you? cc @MelissaBraxton

**Comment by allisonnorman** [comment]
Yes, I completely agree. I was going to bring it up at planning today that we need to make sure we have a solid "we'll know when we're done" here because it could go on forever. The goals you outlined seem like the right scope for now. Thank you!

**Comment by cmajel** [comment]
Since we'll want Jamie's thoughts on this, and there's a lot on the books for the rest of the sprint, we're going to move this back to `to do` to focus on in the next sprint with a narrower focus area.

**Comment by cmajel** [comment]
@allisonnorman per standup, I updated description and closing as we've got #111 to take these learnings forward.
