### ISSUE TITLE
Outline possible risks/harms to G&A users

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#59]
**Background**
In addition to understanding user needs and pain points, we should also outline possible risks and harms to G&A users. 

**Acceptance criteria** 
- [X] We have outlined and documented potential risks and harms to users, and have a way of adding to the list as we learn more - ([Mural](https://app.mural.co/t/gsa6/m/gsa6/1614869435487/95ce8692158f01ebf08ce2df7f4d74d121658a87))

**Tasks**
- [x] Work with SMEs to facilitate and understand risks and harms for users <workshop? synthesis?>. We should probably also give context on equity-centered design practices and why this is important so they learn from this process. 

**Definition of done**
- [X]  Meets acceptance criteria.

**Comment by cmajel** [comment]
Possibly cover in #70

**Comment by cmajel** [comment]
@MelissaBraxton I added a synthesis of possible harms to [the workshop mural](https://app.mural.co/t/gsa6/m/gsa6/1614869435487/95ce8692158f01ebf08ce2df7f4d74d121658a87). 

I do think for a fuller picture, we could revisit as a team to fill in some additional areas. What do you think?

**Comment by allisonnorman** [comment]
@cmajel - I created #122 for further team synthesis and finding a permanent home and updated this issue so we can close.
