### ISSUE TITLE
Research policies to understand how they impact service delivery

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#60]
**Background**
As we begin to explore user needs, pain points, and the system, we should also learn more about how policy impacts service delivery. <Add more context>

**Acceptance criteria** 
- [x] We have a grasp on where policy could impact our work (what requirements exist, policy mandates and restrictions, etc).
- [ ] 

**Tasks**
- [x] Research policies and relevant USFS handbooks
- ~[ ] Talk to policy experts? (Who? From Mural: We need to talk to program managers outside of the research area.)~

**Definition of done**
- [x]  Meets acceptance criteria.

**Comment by MelissaBraxton** [comment]
I've gone ahead and filled out the policy row of the service blueprint, but I haven't identified every relevant handbook section. @cmajel and @allisonnorman  - Since the handbook is often very specific, offering specific guidance for specific roles tailored to individual instrument types, I'm wondering if we want to punt on getting too deep into the handbook until after we've narrowed in a bit. What do y'all think? If you're on board, then I think we can close this and create a new issue for looking at handbook section specific to where we're focusing our first module.

**Comment by MelissaBraxton** [comment]
Also, scratched the policy experts task, since talking to program managers is re: describing their role, not understanding how policy impacts service delivery...
