### ISSUE TITLE
Meet with SMEs to understand the landscape of grants and agreements

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#61]
**Background**
As the team ramps up for the E&I, we should meet with SMEs to better understand the landscape of grants and agreements. For example: 
- Types of grants and agreements
- Processes
- Variability across the org
- Demo of application as needed

[Link to Mural](https://app.mural.co/t/gsa6/m/gsa6/1613157695375/011b2f3d4b2275d948401e7153dac71bb0d8448a) with key research questions.

Note: Depending on the goals of this session, this may be relevant to #58. 

**Acceptance criteria** 
- [x] We have met with SMEs and have a better understanding of the landscape.
- [x] We've updated artifacts with what we've learned (journey map, user role doc).
- [x] We've developed a better relationship with SMEs and know some people we can reach out to in the future. 

**Tasks**
- [x] Meet with Jay and Jamie in advance review journey map, validate our assumptions and fill in gaps. 
- [x] Write protocol for chat (building off of E&I-level research goals from #56) and plan workshop.
- [x] Meet with SMEs
- [x] Document what we've learned
- [ ] Nice to have: Share out to SMEs how we've incorporated their feedback

**Definition of done**
- [x]  Meets acceptance criteria.

**Comment by MelissaBraxton** [comment]
I revised to break out past research synth (#65) and planning and conducting the workshop (#66)

**Comment by MelissaBraxton** [comment]
Moved to waiting. We'll close this out on Friday w/ the journey map review meeting scheduled.

**Comment by MelissaBraxton** [comment]
I think we can move this to done? We won't be meeting with SMEs other than Jay and Jamie and NFS Program Managers (#68) until the workshop.
