### ISSUE TITLE
Align on team agile/planning/task management practices

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#62]
**Background**
As we ramp up and get into the swing of things, we should talk through how we want to approach tracking work now, knowing this process will evolve over time. Some of this will be handled by our Team Charter, but we should also talk about things like:

- How we want to handle subtasks (i.e. when should a task be a card? e.g. Do we want to break out creating an artifact from a research task or have it all in one?)
- How we want to address creating tasks? 
- When/how we pre-plan, making sure we're aligned on the cards before starting work. 
- Acceptance criteria vs definition of done (for where we are now)
- In review column?

**Acceptance criteria** 
- [x] We have a process and workflow for task creating and tracking in GH projects that's working for everyone, feels efficient, and provides autonomy. 

**Tasks**
- [x] Talk about this in planning. 
- [x] Get feedback on initial cards. 
- [x] Check in after going through the process for a couple of weeks. 

**Definition of done**
- [x]  Acceptance criteria met.

**Comment by allisonnorman** [comment]
Where we landed:
- We'll keep an eye on breaking out tasks as needed and check in later on how that's working. It's totally okay to break down issues further and a best practice is to link to the overarching issue.
- To review lane has been added.
- I adjusted the issue template to remove acceptance criteria and definition of done in lieu of a new section, "we'll know we'e done when.."
- We'll pre-plan on alternate Mondays for now.
