### ISSUE TITLE
Refine problem statement and develop product vision statement

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#63]
**Background**
As we learn more about the problem space and paths forward, especially after the design workshops, we should plan and conduct a collaborative session with stakeholders to refine the problem statement and develop a product vision statement. 

[Today's problem statement](https://docs.google.com/presentation/d/1w5xF9nEKB9iAf1KAnzZzpGfWqCjBmopyu8gTZJkXD1k/edit#slide=id.gbbe14bf8a3_1_768)

**We'll know we're done when...** 
- [X] We have collaboratively refined the problem statement and have PO buy-in on it. 
- [X] We have collaboratively developed a clear product vision statement based on what we know today. 

**Tasks**
- [x] Create draft vision Mural and plan collaboration activity ([Mural](https://app.mural.co/t/gsa6/m/gsa6/1615594432130/c2e92bfe7bb2b7bd90a49c19ad0000d60570ed93))
- [x] Schedule activity. (Audience?)
- [X] Jay and Allison to continue to draft vision statement candidates and sync on Thurs.
- [X] Added to draft roadmap

**Comment by cmajel** [comment]
Possible candidate for #70

**Comment by allisonnorman** [comment]
**Vision statement:**
_We are building a new user-friendly, fully digital, web-based application for USFS cooperators and FS staff across regions and stations to centrally and consistently manage agreements from beginning to end.

It will intuitively guide users through the agreement creation and management process, ensuring that policy requirements are met while helping users find and act on information that is relevant to them so that they can focus on the project needs on the ground._  

We'll get more feedback on the initial draft and update the wiki as part of the product framing issue.
