### ISSUE TITLE
Translate project impact tracker Mural into a trackable format & regroup

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#64]
**Background**
We started identifying KPIs that tie to project-specific goals, both in the near and long-term. We should figure out as a team how we want to keep track of our progress towards these goals and KPIs, and how/how often we want to check in on them. 

- [Mural](https://app.mural.co/t/gsa6/m/gsa6/1613141909566/a86e44fe20032c1446efee756c1d887cced51e66)
- [Spreadsheet](https://docs.google.com/spreadsheets/d/1e9-w_LeOMWt6Zbxof0rH4a2eSaOZk9gQnNUWz65_qdU/edit#gid=640289019)

**Acceptance criteria** 
- [x] We have an internal process for checking in on project impact.
- [x] We can tie the goals and KPIs into how we prioritize our work, and know when to correct course. 

**Tasks**
- [X] Move Mural goals and KPIs to spreadsheet template
- [x] Set up co-working to talk through our approach (how we'll use this doc, how we'll track progress, blockers and impediments to our impact.
- [x] Set up a recurring check in to evaluate if we're making the kind of process. 

**Definition of done**
- [x]  Acceptance criteria met.

**Comment by allisonnorman** [comment]
@neilmb @rrefoy - I pulled our Mural goals into the [spreadsheet template](https://docs.google.com/spreadsheets/d/1e9-w_LeOMWt6Zbxof0rH4a2eSaOZk9gQnNUWz65_qdU/edit#gid=640289019). I'm not sure if I'm approaching it correctly as it doesn't seem to line up well with the example. Do we want to pencil this in for coworking this week before some are OOO next week? Can one of you help facilitate the conversation?

**Comment by rrefoy** [comment]
can we use some strategy time for this?

**Comment by rrefoy** [comment]
since we cancelled strategy time, should we find a new time? or use this week's strategy time? do we want to invite Norah and/or Ann?

**Comment by MelissaBraxton** [comment]
We confirmed with project impact team that our [transition plan](https://docs.google.com/document/d/1YOlrpQXbbWwYcE-LYeqoavvMDolHjIgBmfQorp8Ft3c/edit#) tying success scenarios to goals and tasks meets this need.
