### ISSUE TITLE
Review and synthesize past research

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#65]
**Background**
Now that we have a more clear understanding of where we're headed and near term Qs, we want to make sure we have answered as many as we can ourselves drawing on info we've already collected before we reach out to get more info from SMEs. 

**Acceptance criteria** 
- [x] We've reviewed info we have 
- [x] We've documented answers to Qs in shared place
- [x] We've documented remaining knowledge gaps and a plan for filling them in. 
- [x] We've pulled out data we need to create our service blueprint. 

**Tasks**
- [x] Articulate near term Qs that we're likely to be able to answer with the info we already have
   -  Questions from our research planning session in [this scratch pad](https://docs.google.com/document/d/1M7P7YxvvIAG8rdDmSq8VRmdTfl4YxAxEo4eouYjohWQ/edit)
- [x] Review info
- [x] write up answers 
- [x] Highlight remaining Qs
- [x] Create new issues to get answers to remaining Qs. 

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by cmajel** [comment]
From planning, we're scoping this to our initial research questions, and will document a lot of our findings in the scratchpad and point to the service blueprint #67

**Comment by MelissaBraxton** [comment]
@cmajel  - I'm thinking we can go ahead and close this, since the service blue print as well as #60, #61, and #55, cover what remains on this?
