### ISSUE TITLE
Schedule user/stakeholder workshop

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#66]
**Background**

**Acceptance criteria** 
- [x] We've scheduled a workshop with relevant SMEs that will allow us to achieve our workshop goals. 

**Tasks**
- [x] Get list of potential workshop attendees
- [x] Schedule workshop
- [x] Draft workshop goals, 

**Def of done**
- [x] Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Moving to waiting until we get a list of folks we can invite. Sent list to Jay on 2/18.

**Comment by allisonnorman** [comment]
@MelissaBraxton This looks done. Can I close?
