### ISSUE TITLE
Draft service blueprint

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#67]
**Background**
We want to graphically represent our understanding of the current service delivery process to guide further decision making and design activities

**Acceptance criteria** 
- [x] We have a solid draft that we feel confident sharing with SMEs 

**Tasks**
- [x] Review and synthesize past research (#65 )
- [x] Schedule co-working
- [x] Represent the service delivery process in Mural
   * [Service blueprint draft](https://app.mural.co/t/gsa6/m/gsa6/1606250486487/cbe51bccb556bebc4b12c9b98c8201e6cdcea6c3)
- [x] Review with the team
   * Planning to open a new ticket to bring this to SMEs once we have identified a tighter focus areas (like starting a new agreement, post award management)

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Mural is [here](https://app.mural.co/invitation/mural/gsa6/1606250486487?sender=melissabraxton2796&key=2eb65769-a8e3-4e39-8268-63a30449eadc)

**Comment by MelissaBraxton** [comment]
@cmajel  - What do you think we need to do to close this out? We've reviewed w/ the team at a high level in the course of other conversations, but do you want to schedule a walkthrough devoted to it?

**Comment by cmajel** [comment]
@MelissaBraxton I'm adding in notes from the journey map walk through to the blueprint now (it feels like we learned a lot in that convo.) 

Once those updates are in, I think we could close this out and open a new ticket to review a portion of with SMEs, based on our first slice inclinations. It may be overwhelming to review everything right now. 

How does that feel to you?

**Comment by MelissaBraxton** [comment]
That sounds great!



Melissa Braxton
Experience Design, 18F
Cell: 425-770-2349
https://18f.gsa.gov/

**Comment by cmajel** [comment]
@MelissaBraxton @allisonnorman I've added more actions and comments to the [service blueprint](https://app.mural.co/t/gsa6/m/gsa6/1606250486487/cbe51bccb556bebc4b12c9b98c8201e6cdcea6c3) based on our journey map walkthrough with Jay and Jamie, and our recent PM interviews. I also adjusted the ticket description to reflect our future goal to review once we have a tighter focus area.

I feel like we've got the basic format done, and can close this out and move into a living document state. What do you think? Anything we should do before closing out this ticket?

**Comment by allisonnorman** [comment]
I'll defer to @MelissaBraxton but I think we're good to close! Also agree we should create another issue about sharing out for the backlog once we have our focus.

**Comment by MelissaBraxton** [comment]
Sounds good to me!
