### ISSUE TITLE
Write up user role description for NSF program managers

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#68]
**Background**
We heard that there are meaningful difference in how Program Managers at NSF work compared to the research program managers we talked to in the PA. We want to better understand these differences and their implications for design. 

**Acceptance criteria** 
- [x] We've documented user role descriptions for NSF program managers

**Tasks**
- [x] Email Jay for NSF program manager contacts
- [x] Schedule interviews
- [x] Draft protocol
- [x] Conduct interviews
- [x] Synthesize learning in the form of user role descriptions, adding to this [draft](https://docs.google.com/document/d/1WD5a2ma1kXeFpSpjBAmfiWBRxxYC4JNUbDF_WE77ulY/edit) 

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Draft protocol is [here](https://docs.google.com/document/d/1kBdce3RWzoOFJpVlJTxM4FzN9Ivaj8uKcH_ra14Jvcg/edit#), @cmajel if you want to take a look!

**Comment by MelissaBraxton** [comment]
Moving to blocked while we wait to get a list of folks to contact

**Comment by allisonnorman** [comment]
I think this one is unblocked now so moving it to sprint 2!

**Comment by MelissaBraxton** [comment]
Revised description based on recent interviews and workshop input.
