### ISSUE TITLE
Plan and conduct workshop

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#70]
**Background**
Next steps following #66 

**Acceptance criteria** 
- [ ] We've validated our service blueprint with representative users. 

**Tasks**
- [x] Draft workshop agenda, and facilitation script
    * [Agenda / planning doc](https://docs.google.com/document/d/1E2FS7sozrsBb8x_27MHNSp4z4sOnBV8W_Ofo2Zy0YXw/edit)
- [x] Draft deck / Mural template(s)
    * [Workshop deck](https://docs.google.com/presentation/d/1HG80H1QPKSMfJbNhJiDdogNvB3x7gNHXq2Z0LeiOmhU/edit#slide=id.gc28ce93be3_0_0)
- [x] Conduct workshop
   * [Workshop day 1 mural - pain points](https://app.mural.co/t/gsa6/m/gsa6/1614730951506/2d1b2abe3133ead27a0dbf5ca72ba115db38d8c5)
   * [Workshop day 2 - sketching and harms](https://app.mural.co/t/gsa6/m/gsa6/1614869435487/95ce8692158f01ebf08ce2df7f4d74d121658a87)
- [x] Write up insights

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Draft agenda and script shaping up [here](https://docs.google.com/document/d/1E2FS7sozrsBb8x_27MHNSp4z4sOnBV8W_Ofo2Zy0YXw/edit):

**Comment by cmajel** [comment]
@MelissaBraxton @allisonnorman  I started [a slide deck](https://docs.google.com/presentation/d/1HG80H1QPKSMfJbNhJiDdogNvB3x7gNHXq2Z0LeiOmhU/edit#slide=id.gc28ce93be3_0_0) for us to start trying things out.

**Comment by cmajel** [comment]
@MelissaBraxton @allisonnorman I added some notes in the [workshop mural](https://app.mural.co/t/gsa6/m/gsa6/1614869435487/95ce8692158f01ebf08ce2df7f4d74d121658a87) with some top insights to finish this off. Would love review before closing!

A quick topline:
* We got a lot of insight into what would be useful on a personalized dashboard / what you see first when you log into G&A.
* There's a need to see things specific to you, and also need to be able to get to everything. But, personalized should be prioritized. 
* Some of the things most important to see first in a personalized view include...
  * Which agreements have things due (reports, invoices)
  * Agreements with my name on it? (All agreements may be too much)
  * Agreement status, where I am in the process
     * Which agreements/mods are pending?
     * Which agreements are expiring, expired, or need to be closed?
 * We also learned a lot about agreement lookup expectations, including being able to....
   * lookup by forest, region, unit
   * lookup by agreement number
   * lookup by who is involved (PM, cooperator, budget approver)
   * predictive search results and other tools to make search easier
   * Providing search on big lists/dropdowns

**Comment by MelissaBraxton** [comment]
I think we can call this done unless we want to produce a separate write up doc? We have insights documented in the Murals. Is that enough?
