### ISSUE TITLE
Clarify our IIT package/project charter/business case involvement

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#71]
**Background**
Open questions:
- What is our involvement in the IIT package process vs the BA team? Is BA team working on cost analysis only? On business case?
- Could a product framing document fit into and inform this charter?
- How can we make sure there aren't two separate efforts happening at the same time (i.e. the BA team creates something very different than our product framing).
- There's also a business case that accompanies the charter. Maybe we can clarify this to get a better understanding of the whole process? Specifically, get clarity on whether the BA group is using the business case or the charter. 

**Acceptance criteria** 
- [ ] We have an understanding of how we fit into the IIT package (charter, business case) process.
- [ ] We know the timeline of when the BA and/or CIO teams may need to pull from our work. 
- [ ] What else?

**Tasks**
- [x] @MelissaBraxton will respond to thread, clarify BA's involvement and overall timeline. Offer to talk more about this (and potentially show examples)
- [ ] Potentially talk about this in next Wednesday's stakeholder sync
- [ ] Presentation on agile budgeting for stakeholders, potentially?
- [ ] What else?

**Definition of done**
- [ ]  Acceptance criteria is met.

**Comment by MelissaBraxton** [comment]
Moving to waiting until we hear back and/or discuss at next week's Wed. sync.

**Comment by neilmb** [comment]
We will be discussing this at today's sync with Chris and Heather.

**Comment by allisonnorman** [comment]
From backlog grooming: we determined we know next steps and are tracking that in #160.
