### ISSUE TITLE
Create 18F team group/email address

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#72]
**Background**
We want to set up a team email address so that:
1. We don't have to type everyone's name in each time
2. Melissa and/or Neil don't have to triage everything!

**Acceptance criteria** 
- [x] We have a group email and start using it. (It will likely take some time for stakeholders to get used to it)

**Tasks**
- [x] Send request for google group - **18f-usfs-nrm@gsa.gov**
- [x] @allisonnorman to add the team and give everyone management privileges.
- [x] Send a test email to make sure we all get it.
- [x] Update team charter.  

**Definition of done**
- [x]  Acceptance criteria is met.

**Comment by allisonnorman** [comment]
Request #: REQ0586981
