### ISSUE TITLE
Clean up drive

### ISSUE THREAD

**Issue by cmajel** [18F/NRM-Grants-Agreements#75]
**Background**
We're starting a new stage of work with a bigger team, and should verify that our Google drive has homes for future and past work. 

**Acceptance criteria** 
- [x] Team knows where new things go, and where to find old things

**Tasks** To be updated
- [x] Review existing Drive, move items as needed
- [x] Create subfolders for PA work (?)
- [x] Share TOC with team for feedback

**Definition of done**
- [x]  Meets acceptance criteria

**Questions**
- [x] Do we need an acquisition folder?
