### ISSUE TITLE
Try to get access to FEMA grants app repo

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#79]
**Background**
We want to take a look at the grants management app that FEMA is working on to learn whether there's anything we can leverage. We should pursue getting access but based on feedback from @neilmb, he's happy to review the code but it's not likely we can reuse a lot. Let's take that into consideration with how hard we push for access. 

**We'll know we're done when** 
- [ ] We have access to the FEMA code base, or determine we can't get access. 

**Tasks**
- [x] @MCHopson emails FEMA PM to schedule time to meet
- [ ] Follow up with James at USDS to tell him the meeting went well and Alonna was up for us getting read access as a first step. Find out who we need to talk about to get GSA access.
- [ ] Contact Melissa to catch up and mention this to get her read on it.
- [ ] Get access to repo

**Comment by allisonnorman** [comment]
I removed the review and document steps from this issue because I think it's going to take some work to get access. If we do, we can create an issue to review the code and figure out what could be leveraged.

**Comment by allisonnorman** [comment]
From backlog grooming: we decided there are too many hoops to jump through for this and we'll close this issue.
