### ISSUE TITLE
See high-level demo of G&A application

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#8]
**Background**
Before we dive into user interviews in depth, we want to get a high-level understanding of how the application looks, feels, and is used. This demo will help us understand where to dig deeper with users and craft more detailed interview protocols. 

**Acceptance criteria** 
- [x] We've seen a demo of the G&A application

**Tasks**
- [X] Find out from sponsors who can give use the demo
- [X] Schedule ~90~ 60minute demo session with Jennie
- [x] Draft research Qs and probes for demo session
- [x] Document insights from demo in notes 

**Definition of done**
- [x]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Emailed Jennie on 11/23 to schedule.

**Comment by MelissaBraxton** [comment]
Interview guide is [here.](https://docs.google.com/document/d/1W1dXIq8Vg7WCSTn9v7xy76Z0t8J3ED-GJL2tJuSMdIc/edit?usp=sharing)

**Comment by MelissaBraxton** [comment]
This is scheduled for 12/3. Moving to waiting until then!
