### ISSUE TITLE
Create high-level project plan

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#80]
**Background**
Action item coming out of retro, we want to lay out a high level project plan that helps us map our sprints against the project milestone dates laid out in the PA presentation.

**We'll know we're done when**
- [x] We have a high-level plan that we can all look at to plan and track progress, and that can be updated as things change and decisions are made.  

**Tasks**
- [x] Map out dates based on PA presentation to E&I planning Mural
- [X] Review and talk through as a group during strategy time 
- [x] Update the goals based on our team session

**Comment by allisonnorman** [comment]
Work in progress as always, but I've updated the plan as things stand today and will continue to revisit with the team.

**Comment by allisonnorman** [comment]
https://app.mural.co/t/gsa6/m/gsa6/1612470069350/7b4b7b17d33ed20f7c1a396f26a193565e86997c
