### ISSUE TITLE
Set up home for design mocks

### ISSUE THREAD

**Issue by cmajel** [18F/NRM-Grants-Agreements#83]
**Background**
We'll be getting started soon on prototyping different parts of a G&A "first slice." We should plan on having a place for mock ups to live 

**We'll know we're done when...**
- [x] The team knows where to go to look for design mocks
- [x] Designers have a basic set up to get started for first slice

**Tasks**
- [x] Check out USWDS Figma resources vs Sketch 
- [ ] Decide on USFS vs USDA style guide
  * [USDA digital style guide](https://www.usda.gov/digital-strategy/design-and-brand)
  * [USFS style guide from open forest project](https://nciinc.github.io/fs-fork-uswds-site/)
  * Also, [the flagship USFS site](https://www.fs.usda.gov/) has been updated to USWDS. Was a styleguide produced?
- [x] Set up style library in design program (basic colors, type, key components)
- [x] Share with team members
  * [Figma instance here](https://www.figma.com/file/AOWq8IWGSAUGZiqZ1nZSeF/USFS-Grants-and-Agreements-Playground?node-id=1%3A110)

**Comment by cmajel** [comment]
Starting a [playground in Figma here](https://www.figma.com/file/AOWq8IWGSAUGZiqZ1nZSeF/USFS-Grants-and-Agreements-Playground?node-id=1%3A110)

**Comment by cmajel** [comment]
@allisonnorman @MelissaBraxton this is done aside from deciding on the USDA vs FS style guide. I did an exploratory audit of the color mappings across platforms in Figma to get some stuff to work with (and get comfortable with Figma's component system).

I'll close this for now and add a ticket to see if we can get the https://www.fs.usda.gov/ theme file (https://github.com/18F/NRM-Grants-Agreements/issues/105). It seems they did a USWDS color token mapping there.
