### ISSUE TITLE
Scope prototyping an agreements tracking spreadsheet view

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#87]
**Background**
As we explore the nuances of the db and as we identify our first slice, it could be valuable to build a view of data that seems to be commonly used by user research participants to track agreements in various statuses. This will help show the fruits of the labor so far, and also could demonstrate how not only is this kind of optimization possible, it's fairly easy to do. It will also open up the conversation about where we focus our prototyping efforts next. 

**Goals**
- Provide value quickly and reinforce technical path.
- Validate design hypotheses
- Identify other hypotheses for future prototyping.

**In scope**
- [Design/UX] Draft research plan, develop artifacts and probes, and surface any gaps that we may need to code in order to meet user research goals. (Related issues: #117, #125)
- [Design+Engineering] Get more clarity on the data structure and taxonomy of agreements from Jamie (#58)
- [Engineering] Import the contacts table in preparation for further prototyping (#93)
- [Engineering] There may be additional interactive components that will be helpful for user research - TBD

**NOT in scope**
- Authentication - we will use admin login and create a test account.
- Role-based customization, for now. There's a research question we will learn more about. For now, we think the custom views we can use by querying the db are sufficient.
- Further optimizing search. We could optimize more but let's just test and see what comes up from research.
Related artifacts:
- [Workflow ideation Mural](https://app.mural.co/t/gsa6/m/gsa6/1615893047757/79405bdf3cf4550a53b58a5fb232fbbd86b35d24)

Spreadsheet view examples:
- [Example sheet from budget officer](https://docs.google.com/spreadsheets/d/1lhRyhqWQ5xmLLcoOANVXNeNjhKn0-rYP/edit#gid=1304390179)
- [Mural screen shot](https://app.mural.co/t/gsa6/m/gsa6/1606250486487/cbe51bccb556bebc4b12c9b98c8201e6cdcea6c3). 

**We'll know we're done when...**
- [X] We have a design hypothesis and a plan to validate it/get feedback from users.
- [X] We know how deep we need to go that will help unlock engineering and design.

**Tasks**
- [X] @MelissaBraxton to share spreadsheets from participants, though a screen shot of one that could get us started (see above)
- [x] Set up scoping discussion to determine how deep we go on this, based on user needs and technical effort.
- [x] Translate scope into additional tasks based on scope (user stories, design mock ups, etc).

Related issue: #91 

Related user stories:
- As a G&A user, I need to see at a glance, which of my grants or agreements are nearing a milestone so that I can ensure reports, invoices, and closeout are handled on time. 
- As a Grants Specialist, I need to know which agreements are out of compliance, so that I know how to prioritize my time. 
- As a Program Manager, I need to know what invoices, across my entire portfolio, are ready for my approval, so that I can approve them quickly / my cooperators don’t have to wait to get paid.  
- As a Program Manager, I need to know whether I can approve an invoice without going over what is left on the agreement so that I can avoid overpayments and the need for corrections.

**Comment by cmajel** [comment]
Love this! 

@MelissaBraxton do we have the excel that we have screengrabbed in our [service blueprint](https://app.mural.co/t/gsa6/m/gsa6/1606250486487/cbe51bccb556bebc4b12c9b98c8201e6cdcea6c3)? The service blueprint example has some neat distinctions from the [budget officer sheet](https://docs.google.com/spreadsheets/d/1lhRyhqWQ5xmLLcoOANVXNeNjhKn0-rYP/edit#gid=699921556), like:

* Balances
* Program manager assignments (I think that's different from Principle Investigator, who I assume is the cooperator)
* Different statuses (active vs pending closeout)

**Comment by neilmb** [comment]
This has some overlap with #91 which does the technical underpinnings to be able to make a view of this type in the first place. I'd say this comes after that as we figure out how to hook up all of the data that appears in the example spreadsheets.

**Comment by allisonnorman** [comment]
I updated this issue to be a bit higher level, focused on identifying the user needs and overall scope of this that we can create additional issues based on. Hoping we can use this as an exercise to show Jay how we work.

**Comment by allisonnorman** [comment]
We're going to scope this in Thursday's strategy meeting. @neilmb If you get antsy and run out of things to do in the meantime (unlikely!), let me know.

**Comment by allisonnorman** [comment]
Notes from our scoping meeting (likely formatted badly, but I'll make appropriate updates as I work through them): 

**Topics for discussion** 
* What's our goal? When are we "done"? What specifically are we de-risking for the vendor?
- Provide value quickly/reinforce technical path, using the database/prototyping environment, deliver what we can
- Identify other hypotheses that we can share with vendor
- Note: Tradeoff of velocity vs mismatch for long-term experience/technical stack (we should have this conversation)

* What type of data to include, and how we will need to filter that data?
- We're adding tables as we see need for them. 
- Prioritize research plan and determine what we need (what can be answered in Figma, what in admin, etc)
- Talk to Jamie, get her sheet
- Create test account!

* How aligned on our particular flavor of USFS/USWDS for this work? 
- Let's revisit later for future prototyping

* Do we want to factor in role-based customization now?
- Research question pending here

* Will this be in admin or will we need eauth?
- For fake data, we don't need auth, though we need this in Django (which we already have). 

* How will search work?
- Search now is searching 5 fields, not as intuitive as we'd like. We could optimize more but let's test and what people say.

* How will we demo/get feedback/share out the prototype? (how do we factor in the scrubbed data when getting feedback)
- What counts as PII? Grant #, org #, project title aren't PII. Not something we need for next week. 

* How do we want to organize ourselves issue wise? 
- Let's revisit this question
- Tie user stories to work we're doing and fill in Jay
- Add create artifacts to research planning issue

* What are other open questions?
