### ISSUE TITLE
Meet with FS ISSO about prototype policies

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#89]
**Background**

We are working with FS data and developing for them, so we have to get authorization from their CIO's Security and Privacy apparatus for what we are doing. If we were making a publicly available tool, then we would be in their ATO process. For a prototype with limited availability that DOES use production data, and might eventually include PII such as names, we should discuss with them what their policies are.

**We'll know we're done when...**
- [ ] We have had a meeting with the ISSO 
- [ ] We have written down what the policies are for our prototype covering at least the platform, access control, and PII

**Tasks**
- [x] Schedule a meeting
- [ ] After the meeting, write up a document in our Github repo explaining what we understand the policies to be
- [ ] Share the document with FS to make sure that our understanding is accurate.

**Comment by neilmb** [comment]
Re: the meeting described in https://github.com/18F/NRM-Grants-Agreements/issues/49#issuecomment-789959656, the impact for our project is that we are requested NOT to use production data in our prototype/sandbox app.  NRM currently has an open POAM with the FS security team because they DO use production data in their test and dev environments. We don't want to end up in that situation.

Because the G&A data is fiddly and has important relationships between agreements, notes, transactions, etc. we are going try to anonymize the production data instead of creating a synthetic data set that matches the schema (but possibly not the important relationships). We created #102 for that work.
