### ISSUE TITLE
Schedule interviews with G&A users (USFS grants specialists, program managers, budget approvers)

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/NRM-Grants-Agreements#9]
**Background**
We want to talk to folks who use the G&A application so that we can understand their work. 

**Acceptance criteria** 
- [x] Interviews with 3-5 USFS users and a 3-5 public users of the G&A application (grantees or other non-gov groups that enter into agreements with the USFS) are scheduled

**Tasks**
- [x] Get list of possible contacts from G&A point of contact
- [x] Draft recruitment email template
- [x] Set up google calendar appointment slots
- [x] Send scheduling emails
- [x] Send confirmation emails

**Definition of done**
- [x]  Meets acceptance criteria
