### ISSUE TITLE
Develop codesign activity for workshop

### ISSUE THREAD

**Issue by cmajel** [18F/NRM-Grants-Agreements#90]
**Background**
The week of 3/8, we're holding a series of workshops with G&A users to inform our "first slice" direction and check our assumptions. We've discussed using some of this time to codesign what our initial prototype is.

**We'll know we're done when...**
- [x] We have an activity script, and designers have the materials they need to facilitate the activity

**Tasks**
- [x] Decide on prompt (depends on first slice criteria and discussions)
- [x] Design exercise, decide on format (Mural-based? Sketching? Do we need to break out to small groups?)
- [x] Decide how we'll record / gather what's produced
- [x] Decide on how to report out to workshop participants
- [x] What else?

**Questions**
- [x] Will participants have video (for showing sketches)? 
   * Based on conversations with Jay and past FS experience, we believe most participants will have cameras and Edge (Mural compatible). We recognize though that some participants could be audio-only, and should include facilitator guidance if that does happen.

Relates to #70

**Comment by cmajel** [comment]
cc @MelissaBraxton and @allisonnorman. I felt the need to document some thoughts in my head about this, so broke it into a separate issue from workshop planning #70. But also cool folding this into that!

**Comment by MelissaBraxton** [comment]
I think we may want to wait to develop this further until after day 1 is done. What do you think, @cmajel and @allisonnorman. Does this belong back in **to do?**

**Comment by allisonnorman** [comment]
I put it in 'in progress' because we started drafting it but if you think it would be helpful to move it back off the stove until after day 1, that works too!

**Comment by cmajel** [comment]
Agreed. I've started [framing day 2's activities in this mural](https://app.mural.co/t/gsa6/m/gsa6/1614869435487/95ce8692158f01ebf08ce2df7f4d74d121658a87), but I think we'll need day 1 to focus us a bit more.
