### ISSUE TITLE
Use the data we have to make a report or "spreadsheet" view

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#91]
**Background**

Now that we have some grant and authority information in our database, we can use Django to make a first "view" on that data. This doesn't need to be directly useful for FS G&A staff, but we can be guided by what we have seen them use in spreadsheets. Primarily, this is an exercise in hooking up the Django machinery to pull a subset of relevant data from the database and render it onto its own page.

**We'll know we're done when...**
- [ ] We can load a page in our application and see grant information for a subset of grants associated with a single "user" or "organization".

**Tasks**
- [x] Create a Django view with a template and a view method.
- [x] Decide on what subset of data we want to render onto a page.
- [x] Query just the relevant data and put it into the template.

**Comment by tbaxter-18f** [comment]
Is this the same as #87?

**Comment by neilmb** [comment]
I think that #87 is about making a particularly useful view with specific data that is available and this is the pre-work just to be able to make a view and template.

**Comment by allisonnorman** [comment]
I updated #87 to focus more on the scoping of this (how deep do we go?). We'll talk about it in planning!

**Comment by neilmb** [comment]
Technically, it looks like we can take the default Django admin site and add urls to it https://docs.djangoproject.com/en/3.1/ref/contrib/admin/#adding-views-to-admin-sites and be sure to wrap our added views with `admin_site.admin_view` to make them require login.

**Comment by neilmb** [comment]
The initial implementation work is in https://github.com/18F/NRM-Grants-Agreements/tree/91-new-view. It's blocked until we get test data into our local dev environment. Then we can design the query and template to go with it.
