### ISSUE TITLE
Solve our cloud.gov caching/reloading issues

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#92]
**Background**

We have been seeing unexpected behavior on page loads in our cloud.gov app. Sometimes it gives back a response from a (very) old version of the application. Sometimes it gives an error and reloading the error page gets the real page to load. We need to understand why this has been happening and what we should do in our application configuration to prevent it from happening. We'll probably need to see the logs from cloud.gov for a time when it has happened using the `cf logs` command and then track down what instance of the application gave what response.

**We'll know we're done when...**
- [ ] We understand why this has been happening
- [ ] We change our configuration so that it doesn't happen again
- [ ] We write down in the PR or in the YAML file what our understanding is and why the configuration is the way it is

**Tasks**
- [ ] Reproduce the problem
- [ ] Run `cf logs`
- [ ] Look for anomalies
- [ ] Hope that something sticks out as "wrong"

**Comment by neilmb** [comment]
I discovered in the cloud.gov dashboard (dashboard.fr.cloud.gov) a second application called `nrm-fs` in addition to our "real" `fs-nrm` app. They both were responding to traffic on the `fs-nrm.app.cloud.gov` route and so we were seeing exactly what we would expect in that situation, some very old "Hello, World" results and then server errors when the old version of the app didn't understand the URLs that the newer version of the app was putting out.

I deleted the extraneous cloud.gov app and everything looks like it is working now. I'm putting this ticket in review for now until some other people can verify that everything is working right.

**Comment by tbaxter-18f** [comment]
That makes total sense. I created nrm-fs first, then recognized it was backwards (and not aligned with all the other naming) so I _thought_ I was renaming it. Apparently it wasn't renaming it but instead spawned the new app. Nice detective work!
