### ISSUE TITLE
Import more tables into Postgres and use their foreign key relationships

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#93]
**_(Note from Allison: We discussed narrowing scope to importing the contacts table in sprint 3. @tbaxter-18f @neilmb - Can you please update this? I don't want to lose out on the context in the background but wanted to make sure we flagged that as what we said we were hoping to accomplish based on our quick chat)._** 

**Background**
We have the Grants table and the Authorities table. We should import the Notes table and maybe the `II_GA_IP_ACTIVITIES`, `II_GA_IP_CATEGORIES` and `II_GA_IP_COUNTRIES` tables and make sure that we can use the relationship between the `GRANT_CN` foreign key in those tables and the `CN` primary key in the grants table to be able to bring up related information like all of the notes for a single grant or the activities on a single grant

**We'll know we're done when...**
- [ ] We can load a page in our application with grant information and also see data that is loaded from a separate table such as notes or activities.

**Tasks**
- [ ] Import these tables following the process described in (import/README.md)[https://github.com/18F/NRM-Grants-Agreements/blob/main/import/README.md]
- [ ] Create a Django view that uses a JOIN on the grants table and these tables to put combined information onto the page.
- [ ] Import contacts table

**Comment by neilmb** [comment]
Still loading up the notes table which should allow us to connect back to grants with a one-to-many relationship.

**Comment by allisonnorman** [comment]
Narrow scope to contacts table for sprint 3.

**Comment by neilmb** [comment]
Done loading the accomplishment instruments table. Working now on accomplishment instrument/contacts links table. The final one is the contacts themselves.

**Comment by tbaxter-18f** [comment]
At this point we've scrubbed the data and built models. I'd like to make one more pass it, get the new items in the admin, and have one more look at the models before closing this out.
