### ISSUE TITLE
Set up CircleCI for linting and automated testing

### ISSUE THREAD

**Issue by neilmb** [18F/NRM-Grants-Agreements#94]
**Background**

We want to set a good example in our development practices, so we should set up automated testing and automated code quality checking.

**We'll know we're done when...**
- [ ] CircleCI is automatically running on each PR and merge to main, and merges can't happen unless tests are passing.

**Tasks**
- [x] Configure CircleCI. Steal from someone else, maybe https://github.com/18F/tock/blob/main/.circleci/config.yml
- [ ] Make a test PR and check that our tests ran and that merging is blocked when they fail.

**Comment by neilmb** [comment]
I set up branch protection rule https://github.com/18F/NRM-Grants-Agreements/settings/branch_protection_rules/19639822 to enforce tests passing on merges to main.
