### ISSUE TITLE
Follow up on technical decision

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#95]
**Background**
As we identify the first slice and module, and begin to roadmap out the prototyping work, we need to ensure that we have alignment with stakeholders and decision makers on the modular approach.

**We'll know we're done when...**
- [ ] We have a final decision on the technical direction and can move full steam ahead. 

**Tasks**
- [ ] Confirm at Wednesday sync
OR
- [ ] Follow up with stakeholders via email or separate meeting.

**Comment by allisonnorman** [comment]
Update: Added this as a necessary decision in 3/26 weekly ship

**Comment by allisonnorman** [comment]
We chatted about this in backlog grooming. We will find this out as part of the IRB review, so closing this issue as it's folded into that process. Related issue: #160
