### ISSUE TITLE
Decide on first focus area/epic

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#96]
**Background**
Based on what we've learned so far, we want to choose our first area of focus that will help set the foundation for the next few weeks of work, and will inform the RFQ process. There's so much more background than can fit here, but this issue is to track the decision as it's essential to make soon in order to hit our overall project timelines. 

[Slice criteria scratchpad](https://docs.google.com/document/d/12MMJSCMmdHgDmTjZ_Pw6H6d5IQrCZDSbyMIs88wqzXI/edit)

**We'll know we're done when...**
- [x] We know the first slice/first epic we will work on, and have enough context to begin scoping.
- [x] We see how this fits into a broader module and can begin articulating this in a draft RFQ.
- [x] We've identified what technical dependencies we need to focus on to begin prototyping.

**Tasks**
- [x] See related issues/dependencies. There is a lot that will lead us here!

Related issues/dependencies:
- Follow up on technical decision #95
- [Plan and conduct workshops #70](https://github.com/18F/NRM-Grants-Agreements/issues/70)
- [Develop codesign activity for workshop #90](https://github.com/18F/NRM-Grants-Agreements/issues/90)
- [Meet with FS ISSO about prototype policies #89](https://github.com/18F/NRM-Grants-Agreements/issues/89)
