### ISSUE TITLE
Get CO assigned

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#97]
**Background**
In order to ensure we have time to onboard and co-work with the vendor, we are targeting to award a contract **by early May**. We need to understand the process for getting a CO assigned, and the timeline and process for working with that CO to get the RFQ published and contract awarded. Jay has mentioned this is a risk because it's unclear what that process is or how long it will take. We need to de-risk that. 

**We'll know we're done when...**
- [ ] We have a CO assigned.
- [ ] We've talked with the CO or contracting team and understand overall timelines and processes we need to follow for the RFQ and awarding a vendor contract for module 1. 

**Tasks**
- [ ] Talk to Miatta about what's been done
- [ ] Share draft RFQ (#103) with Nick to understand his involvement and next steps
- [ ] Brief the CO on this project and learn what their process and timeline is to ensure we can hit our goal date of mid-May.

(Note: Allison is not an acquisition expert so feel free to edit!)

**Comment by allisonnorman** [comment]
Closing this as we've merged this with #151.
