### ISSUE TITLE
Prioritize user needs and pain points

### ISSUE THREAD

**Issue by allisonnorman** [18F/NRM-Grants-Agreements#99]
**Background**
As we explore various paths for module 1 and the first slice, we want to translate what we learn from the design sessions and other stakeholder meetings to inform a prioritization framework for user needs and pain points.

The way I'm thinking about is to think of these needs and pain points holistically to be able to understand a longer horizon of work and to inform potential future modules, and then to narrow in more specifically on needs and pain points related to slice 1. 

This is related to #63 and together, will help us prep for product framing and roadmapping.

**We'll know we're done when...**
- [x] We have prioritized focus areas/slices and have a sense of where they fit in (module 1, module 2, etc)
- [x] We have a list of prioritized pain points and needs that we can begin translating into user stories

**Tasks**
- [X] Figure out a system for prioritizing pain points vs organization realities
- [X] Work with Christine and Melissa to figure out how/if we can get at this in the workshops
- [X] Conduct prioritization workshop on 3/4/21
- [x] Synthesize/reframe pain points against slice criteria and module opportunities
- [x] Work with Jay and Jamie to review and refine prioritization

**Comment by MelissaBraxton** [comment]
From my perspective, I think we could close this out. We have a great start in the RFQ and will keep refining as we go.
